version: '3.5'
services:
 web_dev:
  build: .
  ports:
   - "80:80"
  volumes:
   - .:/app
  environment:
   - ENV=development
   - PORT=80
   - DB=mongodb://mongodb:27017/todoDev

networks:
 default:
  name: web_dev