(function(g){var window=this;var mpa=function(a,b){return g.Vb(a,b)},Y3=function(){},npa=function(a){if(a.zc&&"function"==typeof a.zc)return a.zc();
if(g.v(a))return a.split("");if(g.Na(a)){for(var b=[],c=a.length,d=0;d<c;d++)b.push(a[d]);return b}return g.Rb(a)},opa=function(a,b){if(a.forEach&&"function"==typeof a.forEach)a.forEach(b,void 0);
else if(g.Na(a)||g.v(a))(0,g.B)(a,b,void 0);else{if(a.Dd&&"function"==typeof a.Dd)var c=a.Dd();else if(a.zc&&"function"==typeof a.zc)c=void 0;else if(g.Na(a)||g.v(a)){c=[];for(var d=a.length,e=0;e<d;e++)c.push(e)}else c=g.Sb(a);d=npa(a);e=d.length;for(var f=0;f<e;f++)b.call(void 0,d[f],c&&c[f],a)}},Z3=function(a){g.Vm(a,"zx",g.sc());
return a},$3=function(a,b,c){g.Ma(c)||(c=[String(c)]);
g.$m(a.l,b,c)},a4=function(a){return(a=g.ro(a))?new ActiveXObject(a):new XMLHttpRequest},b4=function(a,b){return b+" ["+a.aa+" "+a.F+" "+a.getStatus()+"]"},ppa=function(a){return"content-type"==a.toLowerCase()},c4=function(a){a.g&&a.I&&(a.g.ontimeout=null);
a.B&&(g.w.clearTimeout(a.B),a.B=null)},qpa=function(a){return g.Nd&&g.Dc(9)&&g.Ga(a.timeout)&&g.Ea(a.ontimeout)},d4=function(a){a.O||(a.O=!0,a.dispatchEvent("complete"),a.dispatchEvent("error"))},e4=function(a,b){if(a.g){c4(a);
var c=a.g,d=a.P[0]?g.Ia:null;a.g=null;a.P=null;b||a.dispatchEvent("ready");try{c.onreadystatechange=d}catch(e){}}},f4=function(a,b){a.i=!1;
a.g&&(a.o=!0,a.g.abort(),a.o=!1);a.l=b;a.u=5;d4(a);e4(a)},g4=function(a){return a.g?a.g.readyState:0},h4=function(a){if(a.i&&"undefined"!=typeof g.FX)if(a.P[1]&&4==g4(a)&&2==a.getStatus())b4(a,"Local request error detected and ignored");
else if(a.D&&4==g4(a))g.Dg(a.Hv,0,a);else if(a.dispatchEvent("readystatechange"),4==g4(a)){b4(a,"Request complete");a.i=!1;try{var b=a.getStatus();a:switch(b){case 200:case 201:case 202:case 204:case 206:case 304:case 1223:var c=!0;break a;default:c=!1}var d;if(!(d=c)){var e;if(e=0===b){var f=g.Ng(String(a.F))[1]||null;if(!f&&g.w.self&&g.w.self.location){var k=g.w.self.location.protocol;f=k.substr(0,k.length-1)}e=!rpa.test(f?f.toLowerCase():"")}d=e}if(d)a.dispatchEvent("complete"),a.dispatchEvent("success");
else{a.u=6;try{var l=2<g4(a)?a.g.statusText:""}catch(m){l=""}a.l=l+" ["+a.getStatus()+"]";d4(a)}}finally{e4(a)}}},i4=function(a){g.Qf.call(this);
this.headers=new g.Km;this.M=a||null;this.i=!1;this.P=this.g=null;this.aa=this.F="";this.u=0;this.l="";this.o=this.V=this.D=this.O=!1;this.A=0;this.B=null;this.Y="";this.I=this.R=!1},j4=function(a){try{return a.g?a.g.responseText:""}catch(b){return""}},spa=function(a,b){var c=[];
g.Kk(b,function(d){try{var e=g.Go.prototype.i.call(this,d,!0)}catch(f){if("Storage: Invalid value was encountered"==f)return;throw f;}g.Ea(e)?g.Fo(e)&&c.push(d):c.push(d)},a);
return c},tpa=function(a,b){var c=spa(a,b);
(0,g.B)(c,function(d){g.Go.prototype.remove.call(this,d)},a)},k4=function(a){if(a.Xc){if(a.Xc.locationOverrideToken)return{locationOverrideToken:a.Xc.locationOverrideToken};
if(null!=a.Xc.latitudeE7&&null!=a.Xc.longitudeE7)return{latitudeE7:a.Xc.latitudeE7,longitudeE7:a.Xc.longitudeE7}}return null},upa=function(a,b){g.ab(a,b)||a.push(b)},l4=function(a){var b=0,c;
for(c in a)b++;return b},vpa=function(a){return/^\s*$/.test(a)?!1:/^[\],:{}\s\u2028\u2029]*$/.test(a.replace(/\\["\\\/bfnrtu]/g,"@").replace(/(?:"[^"\\\n\r\u2028\u2029\x00-\x08\x0a-\x1f]*"|true|false|null|-?\d+(?:\.\d*)?(?:[eE][+\-]?\d+)?)[\s\u2028\u2029]*(?=:|,|]|}|$)/g,"]").replace(/(?:^|:|,)(?:[\s\u2028\u2029]*\[)+/g,""))},wpa=function(a){try{return g.w.JSON.parse(a)}catch(d){var b=d}a=String(a);
if(vpa(a))try{var c=eval("("+a+")");b&&(0,g.FW)("Invalid JSON: "+a,b);return c}catch(d){}throw Error("Invalid JSON string: "+a);},xpa=function(a,b,c,d){var e=new g.Nm(null,void 0);
a&&g.Om(e,a);b&&g.Pm(e,b);c&&g.Qm(e,c);d&&(e.i=d);return e},m4=function(a){if(g.w.JSON)try{return g.w.JSON.parse(a)}catch(b){}return wpa(a)},n4=function(){this.g=[];
this.i=[]},o4=function(a,b){g.Lp[a]=!0;
var c=g.Jp();c&&c.publish.apply(c,arguments);g.Lp[a]=!1},p4=function(a){this.app=this.name=this.id="";
this.type="REMOTE_CONTROL";this.obfuscatedGaiaId=this.avatar=this.username="";this.l=!1;this.capabilities=new Set;this.experiments=new Set;this.theme="u";new g.Km;this.g=this.i="";a&&(this.id=a.id||a.name,this.name=a.name,this.app=a.app,this.type=a.type||"REMOTE_CONTROL",this.username=a.user||"",this.avatar=a.userAvatarUri||"",this.obfuscatedGaiaId=a.obfuscatedGaiaId||"",this.theme=a.theme||"u",ypa(this,a.capabilities||""),zpa(this,a.experiments||""),this.i=a.remoteControllerUrl||"",this.g=a.localChannelEncryptionKey||
"")},ypa=function(a,b){a.capabilities.clear();
(0,g.Zd)(b.split(","),g.Sa(mpa,Apa)).forEach(function(c){a.capabilities.add(c)})},zpa=function(a,b){a.experiments.clear();
b.split(",").forEach(function(c){a.experiments.add(c)})},q4=function(a){a=a||{};
this.name=a.name||"";this.id=a.id||a.screenId||"";this.token=a.token||a.loungeToken||"";this.uuid=a.uuid||a.dialId||""},r4=function(a,b){return!!b&&(a.id==b||a.uuid==b)},s4=function(a){return{name:a.name,
screenId:a.id,loungeToken:a.token,dialId:a.uuid}},Bpa=function(a){return new q4(a)},t4=function(a){return g.Ma(a)?(0,g.G)(a,Bpa):[]},u4=function(a){return a?'{name:"'+a.name+'",id:'+a.id.substr(0,6)+"..,token:"+(a.token?".."+a.token.slice(-6):"-")+",uuid:"+(a.uuid?".."+a.uuid.slice(-6):"-")+"}":"null"},v4=function(a){return g.Ma(a)?"["+(0,g.G)(a,u4).join(",")+"]":"null"},w4=function(){return"xxxxxxxx-xxxx-4xxx-yxxx-xxxxxxxxxxxx".replace(/[xy]/g,function(a){var b=16*Math.random()|0;
return("x"==a?b:b&3|8).toString(16)})},Cpa=function(a){return(0,g.G)(a,function(b){return{key:b.id,
name:b.name}})},x4=function(a,b){return g.Ya(a,function(c){return c||b?!c!=!b?!1:c.id==b.id:!0})},y4=function(a,b){return g.Ya(a,function(c){return r4(c,b)})},Dpa=function(){var a=(0,g.Xs)();
a&&tpa(a,a.g.bf(!0))},z4=function(){var a=g.$s("yt-remote-connected-devices")||[];
g.rb(a);return a},Epa=function(a){if(0==a.length)return[];
var b=a[0].indexOf("#"),c=-1==b?a[0]:a[0].substring(0,b);return(0,g.G)(a,function(d,e){return 0==e?d:d.substring(c.length)})},A4=function(a){g.Zs("yt-remote-connected-devices",a,86400)},C4=function(){if(B4)return B4;
var a=g.$s("yt-remote-device-id");a||(a=w4(),g.Zs("yt-remote-device-id",a,31536E3));for(var b=z4(),c=1,d=a;g.ab(b,d);)c++,d=a+"#"+c;return B4=d},D4=function(){var a=z4(),b=C4();
g.ab(a,b);g.bt()&&g.tb(a,b);a=Epa(a);if(0==a.length)try{g.ys("remote_sid")}catch(c){}else try{g.xs("remote_sid",a.join(","),-1)}catch(c){}},E4=function(){return g.$s("yt-remote-session-browser-channel")},F4=function(){return g.$s("yt-remote-local-screens")||[]},G4=function(){g.Zs("yt-remote-lounge-token-expiration",!0,86400)},Fpa=function(a){5<a.length&&(a=a.slice(a.length-5));
var b=(0,g.G)(F4(),function(d){return d.loungeToken}),c=(0,g.G)(a,function(d){return d.loungeToken});
(0,g.$i)(c,function(d){return!g.ab(b,d)})&&G4();
g.Zs("yt-remote-local-screens",a,31536E3)},Gpa=function(a,b){g.Zs("yt-remote-session-browser-channel",a);
g.Zs("yt-remote-session-screen-id",b);var c=z4(),d=C4();g.ab(c,d)||c.push(d);A4(c);D4()},H4=function(a){a||(g.at("yt-remote-session-screen-id"),g.at("yt-remote-session-video-id"));
D4();a=z4();g.db(a,C4());A4(a)},J4=function(){if(!I4){var a=g.Qo();
a&&(I4=new g.Ao(a))}return I4?!!I4.get("yt-remote-use-staging-server"):!1},K4=function(a){return!!document.currentScript&&(-1!=document.currentScript.src.indexOf("?"+a)||-1!=document.currentScript.src.indexOf("&"+a))},L4=function(){return"function"==typeof window.__onGCastApiAvailable?window.__onGCastApiAvailable:null},N4=function(a){a.length?M4(a.shift(),function(){N4(a)}):O4()},Hpa=function(a){return"chrome-extension://"+a+P4},M4=function(a,b,c){var d=document.createElement("script");
d.onerror=b;c&&(d.onload=c);d.src=a;(document.head||document.documentElement).appendChild(d)},O4=function(){var a=L4();
a&&a(!1,"No cast extension found")},Q4=function(){if(Ipa){var a=2,b=L4(),c=function(){a--;
0==a&&b&&b(!0)};
window.__onGCastApiAvailable=c;M4("//www.gstatic.com/cast/sdk/libs/sender/1.0/cast_framework.js",O4,c)}},Jpa=function(){Q4();
var a=window.navigator.userAgent.match(/Chrome\/([0-9]+)/);N4(["//www.gstatic.com/eureka/clank/"+(a?parseInt(a[1],10):0)+P4,"//www.gstatic.com/eureka/clank"+P4])},R4=function(a,b,c){g.H.call(this);
this.A=null!=c?(0,g.z)(a,c):a;this.Tc=b;this.u=(0,g.z)(this.MC,this);this.g=!1;this.i=0;this.l=this.za=null;this.o=[]},S4=function(){},T4=function(a,b,c,d){this.g=a;
this.l=b;this.B=c;this.A=d||1;this.o=45E3;this.ba=new g.an(this);this.i=new g.Cg;this.i.setInterval(250)},V4=function(a,b,c){a.Ph=1;
a.Zf=Z3(b.clone());a.kh=c;a.u=!0;U4(a,null)},W4=function(a,b,c,d,e){a.Ph=1;
a.Zf=Z3(b.clone());a.kh=null;a.u=c;e&&(a.zz=!1);U4(a,d)},U4=function(a,b){a.si=(0,g.C)();
X4(a);a.vg=a.Zf.clone();$3(a.vg,"t",a.A);a.Kk=0;a.tc=a.g.Vo(a.g.Bk()?b:null);0<a.Cp&&(a.mn=new g.wl((0,g.z)(a.IA,a,a.tc),a.Cp));a.ba.da(a.tc,"readystatechange",a.uL);var c=a.Qg?g.cc(a.Qg):{};a.kh?(a.Wn="POST",c["Content-Type"]="application/x-www-form-urlencoded",a.tc.send(a.vg,a.Wn,a.kh,c)):(a.Wn="GET",a.zz&&!g.Pd&&(c.Connection="close"),a.tc.send(a.vg,a.Wn,null,c));a.g.ne(1)},d5=function(a,b,c){for(var d=!0;!a.Gg&&a.Kk<c.length;){var e=Kpa(a,c);
if(e==Y4){4==b&&(a.ag=4,Z4(15),d=!1);break}else if(e==$4){a.ag=4;Z4(16);d=!1;break}else a5(a,e)}4==b&&0==c.length&&(a.ag=1,Z4(17),d=!1);a.se=a.se&&d;d||(b5(a),c5(a))},Kpa=function(a,b){var c=a.Kk,d=b.indexOf("\n",c);
if(-1==d)return Y4;c=Number(b.substring(c,d));if(isNaN(c))return $4;d+=1;if(d+c>b.length)return Y4;var e=b.substr(d,c);a.Kk=d+c;return e},g5=function(a,b){a.si=(0,g.C)();
X4(a);var c=b?window.location.hostname:"";a.vg=a.Zf.clone();g.Vm(a.vg,"DOMAIN",c);g.Vm(a.vg,"t",a.A);try{a.we=new ActiveXObject("htmlfile")}catch(n){b5(a);a.ag=7;Z4(22);c5(a);return}var d="<html><body>";if(b){for(var e="",f=0;f<c.length;f++){var k=c.charAt(f);if("<"==k)e+="\\x3c";else if(">"==k)e+="\\x3e";else{var l=k;if(l in e5)k=e5[l];else if(l in f5)k=e5[l]=f5[l];else{var m=l.charCodeAt(0);if(31<m&&127>m)k=l;else{if(256>m){if(k="\\x",16>m||256<m)k+="0"}else k="\\u",4096>m&&(k+="0");k+=m.toString(16).toUpperCase()}k=
e5[l]=k}e+=k}}d+='<script>document.domain="'+e+'"\x3c/script>'}c=g.md(g.Lc("b/12014412"),d+"</body></html>");a.we.open();a.we.write(g.hd(c));a.we.close();a.we.parentWindow.m=(0,g.z)(a.OK,a);a.we.parentWindow.d=(0,g.z)(a.Hy,a,!0);a.we.parentWindow.rpcClose=(0,g.z)(a.Hy,a,!1);c=a.we.createElement("DIV");a.we.parentWindow.document.body.appendChild(c);d=g.Xc(a.vg.toString());d=g.oc(g.Uc(d));d=g.md(g.Lc("b/12014412"),'<iframe src="'+d+'"></iframe>');g.nd(c,d);a.g.ne(1)},X4=function(a){a.Ks=(0,g.C)()+a.o;
h5(a,a.o)},h5=function(a,b){if(null!=a.Ii)throw Error("WatchDog timer not null");
a.Ii=i5((0,g.z)(a.YK,a),b)},j5=function(a){a.Ii&&(g.w.clearTimeout(a.Ii),a.Ii=null)},c5=function(a){a.g.Fv()||a.Gg||a.g.Wm(a)},b5=function(a){j5(a);
g.qf(a.mn);a.mn=null;a.i.stop();g.cn(a.ba);if(a.tc){var b=a.tc;a.tc=null;b.abort();b.dispose()}a.we&&(a.we=null)},a5=function(a,b){try{a.g.By(a,b),a.g.ne(4)}catch(c){}},l5=function(a,b,c,d,e){if(0==d)c(!1);
else{var f=e||0;d--;k5(a,b,function(k){k?c(!0):g.w.setTimeout(function(){l5(a,b,c,d,f)},f)})}},k5=function(a,b,c){var d=new Image;
d.onload=function(){try{m5(d),c(!0)}catch(e){}};
d.onerror=function(){try{m5(d),c(!1)}catch(e){}};
d.onabort=function(){try{m5(d),c(!1)}catch(e){}};
d.ontimeout=function(){try{m5(d),c(!1)}catch(e){}};
g.w.setTimeout(function(){if(d.ontimeout)d.ontimeout()},b);
d.src=a},m5=function(a){a.onload=null;
a.onerror=null;a.onabort=null;a.ontimeout=null},n5=function(a){this.g=a;
this.i=new S4},p5=function(a){var b=o5(a.g,a.Ti,"/mail/images/cleardot.gif");
Z3(b);l5(b.toString(),5E3,(0,g.z)(a.YB,a),3,2E3);a.ne(1)},r5=function(a){var b=a.g.F;
if(null!=b)Z4(5),b?(Z4(11),q5(a.g,a,!1)):(Z4(12),q5(a.g,a,!0));else if(a.zd=new T4(a,void 0,void 0,void 0),a.zd.Qg=a.Ap,b=a.g,b=o5(b,b.Bk()?a.zj:null,a.Bp),Z4(5),!g.Nd||g.Ec(10))$3(b,"TYPE","xmlhttp"),W4(a.zd,b,!1,a.zj,!1);else{$3(b,"TYPE","html");var c=a.zd;a=!!a.zj;c.Ph=3;c.Zf=Z3(b.clone());g5(c,a)}},s5=function(a,b,c){this.g=1;
this.i=[];this.o=[];this.u=new S4;this.D=a||null;this.F=null!=b?b:null;this.A=c||!1},Lpa=function(a,b){this.g=a;
this.map=b;this.context=null},t5=function(a){g.sf.call(this,"statevent",a)},u5=function(a,b){g.sf.call(this,"timingevent",a);
this.size=b},v5=function(a){g.sf.call(this,"serverreachability",a)},z5=function(a){w5(a);
if(3==a.g){var b=a.gk++,c=a.Kl.clone();g.Vm(c,"SID",a.l);g.Vm(c,"RID",b);g.Vm(c,"TYPE","terminate");x5(a,c);b=new T4(a,a.l,b,void 0);b.Ph=2;b.Zf=Z3(c.clone());(new Image).src=b.Zf;b.si=(0,g.C)();X4(b)}y5(a)},B5=function(a){a.pC(1,0);
a.Kl=o5(a,null,a.zp);A5(a)},w5=function(a){a.Rf&&(a.Rf.abort(),a.Rf=null);
a.Sb&&(a.Sb.cancel(),a.Sb=null);a.df&&(g.w.clearTimeout(a.df),a.df=null);C5(a);a.wd&&(a.wd.cancel(),a.wd=null);a.Wf&&(g.w.clearTimeout(a.Wf),a.Wf=null)},D5=function(a,b){if(0==a.g)throw Error("Invalid operation: sending map when state is closed");
a.i.push(new Lpa(a.ZG++,b));2!=a.g&&3!=a.g||A5(a)},A5=function(a){a.wd||a.Wf||(a.Wf=i5((0,g.z)(a.Gy,a),0),a.Kh=0)},G5=function(a,b){if(1==a.g){if(!b){a.gk=Math.floor(1E5*Math.random());
var c=a.gk++,d=new T4(a,"",c,void 0);d.Qg=null;var e=E5(a),f=a.Kl.clone();g.Vm(f,"RID",c);g.Vm(f,"CVER","1");x5(a,f);V4(d,f,e);a.wd=d;a.g=2}}else 3==a.g&&(b?F5(a,b):0==a.i.length||a.wd||F5(a))},F5=function(a,b){if(b)if(6<a.Hg){a.i=a.o.concat(a.i);
a.o.length=0;var c=a.gk-1;var d=E5(a)}else c=b.B,d=b.kh;else c=a.gk++,d=E5(a);var e=a.Kl.clone();g.Vm(e,"SID",a.l);g.Vm(e,"RID",c);g.Vm(e,"AID",a.Zh);x5(a,e);c=new T4(a,a.l,c,a.Kh+1);c.Qg=null;c.setTimeout(1E4+Math.round(1E4*Math.random()));a.wd=c;V4(c,e,d)},x5=function(a,b){if(a.Sc){var c=a.Sc.fv();
c&&g.Lb(c,function(d,e){g.Vm(b,e,d)})}},E5=function(a){var b=Math.min(a.i.length,1E3),c=["count="+b];
if(6<a.Hg&&0<b){var d=a.i[0].g;c.push("ofs="+d)}else d=0;for(var e=0;e<b;e++){var f=a.i[e].g,k=a.i[e].map;f=6>=a.Hg?e:f-d;try{g.Lb(k,function(l,m){c.push("req"+f+"_"+m+"="+encodeURIComponent(l))})}catch(l){c.push("req"+f+"_type="+encodeURIComponent("_badmap"))}}a.o=a.o.concat(a.i.splice(0,b));
return c.join("&")},H5=function(a){a.Sb||a.df||(a.B=1,a.df=i5((0,g.z)(a.Fy,a),0),a.Eh=0)},J5=function(a){if(a.Sb||a.df||3<=a.Eh)return!1;
a.B++;a.df=i5((0,g.z)(a.Fy,a),I5(a,a.Eh));a.Eh++;return!0},q5=function(a,b,c){a.Un=c;
a.Ee=b.sf;a.A||B5(a)},C5=function(a){null!=a.Lg&&(g.w.clearTimeout(a.Lg),a.Lg=null)},I5=function(a,b){var c=5E3+Math.floor(1E4*Math.random());
a.isActive()||(c*=2);return c*b},L5=function(a,b){if(2==b||9==b){var c=null;
a.Sc&&(c=null);var d=(0,g.z)(a.XL,a);c||(c=new g.Nm("//www.google.com/images/cleardot.gif"),Z3(c));k5(c.toString(),1E4,d)}else Z4(2);K5(a,b)},K5=function(a,b){a.g=0;
a.Sc&&a.Sc.lu(b);y5(a);w5(a)},y5=function(a){a.g=0;
a.Ee=-1;if(a.Sc)if(0==a.o.length&&0==a.i.length)a.Sc.Lo();else{g.ib(a.o);var b=g.ib(a.i);a.o.length=0;a.i.length=0;a.Sc.Lo(b)}},o5=function(a,b,c){var d=g.Wm(c);
if(""!=d.g)b&&g.Pm(d,b+"."+d.g),g.Qm(d,d.u);else{var e=window.location;d=xpa(e.protocol,b?b+"."+e.hostname:e.hostname,+e.port,c)}a.gj&&g.Lb(a.gj,function(f,k){g.Vm(d,k,f)});
g.Vm(d,"VER",a.Hg);x5(a,d);return d},i5=function(a,b){if(!g.Oa(a))throw Error("Fn must not be null and must be a function");
return g.w.setTimeout(function(){a()},b)},Z4=function(a){M5.dispatchEvent(new t5(M5,a))},N5=function(){},Mpa=function(a,b){this.action=a;
this.params=b||{}},O5=function(a,b){g.H.call(this);
this.g=new g.N(this.GK,0,this);g.I(this,this.g);this.Tc=5E3;this.i=0;if(g.Oa(a))b&&(a=(0,g.z)(a,b));else if(a&&g.Oa(a.handleEvent))a=(0,g.z)(a.handleEvent,a);else throw Error("Invalid listener argument");this.l=a},P5=function(a,b,c){this.H=a;
this.A=b;this.l=new g.zo;this.i=new O5(this.tM,this);this.g=null;this.Za=!1;this.u=null;this.F="";this.D=this.o=0;this.B=[];this.I=c||!1},Npa=function(a){return{firstTestResults:[""],
secondTestResults:!a.g.Un,sessionId:a.g.l,arrayId:a.g.Zh}},Q5=function(a,b){a.D=b||0;
a.i.stop();a.g&&(3==a.g.g&&G5(a.g),z5(a.g));a.D=0},R5=function(a){return!!a.g&&3==a.g.g},Opa=function(a,b){(a.A.loungeIdToken=b)||a.i.stop()},S5=function(a){this.port=this.domain="";
this.g="/api/lounge";this.i=!0;a=a||document.location.href;var b=g.Qg(a)||"";b&&(this.port=":"+b);this.domain=g.Pg(a)||"";a=g.Jb;0<=a.search("MSIE")&&(a=a.match(/MSIE ([\d.]+)/)[1],0>g.Ib(a,"10.0")&&(this.i=!1))},T5=function(a,b){var c=a.g;
if(g.Ea(void 0)?0:a.i)c="https://"+a.domain+a.port+a.g;return g.Zg(c+b,{})},U5=function(a,b,c,d,e){a={format:"JSON",
method:"POST",context:a,timeout:5E3,withCredentials:!1,onSuccess:g.Sa(a.o,d,!0),onError:g.Sa(a.l,e),nd:g.Sa(a.u,e)};c&&(a.qb=c,a.headers={"Content-Type":"application/x-www-form-urlencoded"});return g.vq(b,a)},Ppa=function(){var a=V5;
W5();X5.push(a);Y5(X5)},Z5=function(a,b){W5();
var c=X5,d=Qpa(a,String(b));0==c.length?Rpa(d):(Y5(c),(0,g.B)(c,function(e){e(d)}))},W5=function(){X5||(X5=g.x("yt.mdx.remote.debug.handlers_")||[],g.Ha("yt.mdx.remote.debug.handlers_",X5,void 0))},Rpa=function(a){var b=($5+1)%50;
$5=b;a6[b]=a;b6||(b6=49==b)},Y5=function(a){var b=a6;
if(b[0]){var c=$5,d=b6?c:-1;do{d=(d+1)%50;var e=b[d];(0,g.B)(a,function(f){f(e)})}while(d!=c);
a6=Array(50);$5=-1;b6=!1}},Qpa=function(a,b){var c=((0,g.C)()-Spa)/1E3;
c.toFixed&&(c=c.toFixed(3));var d=[];d.push("[",c+"s","] ");d.push("[","yt.mdx.remote","] ");d.push(a+": "+b,"\n");return d.join("")},c6=function(a){g.Q.call(this);
this.B=a;this.g=[]},d6=function(a,b){var c=a.get(b.uuid)||a.get(b.id);
if(c){var d=c.name;c.id=b.id||c.id;c.name=b.name;c.token=b.token;c.uuid=b.uuid||c.uuid;return c.name!=d}a.g.push(b);return!0},Tpa=function(a,b){var c=a.g.length!=b.length;
a.g=(0,g.Zd)(a.g,function(f){return!!x4(b,f)});
for(var d=0,e=b.length;d<e;d++)c=d6(a,b[d])||c;return c},Upa=function(a,b){var c=a.g.length;
a.g=(0,g.Zd)(a.g,function(d){return!(d||b?!d!=!b?0:d.id==b.id:1)});
return a.g.length<c},e6=function(a,b,c,d){g.Q.call(this);
this.A=a;this.u=b;this.l=c;this.o=d;this.i=0;this.g=null;this.za=NaN},g6=function(a){c6.call(this,"LocalScreenService");
this.l=a;this.i=NaN;f6(this);this.info("Initializing with "+v4(this.g))},h6=function(a){if(a.g.length){var b=(0,g.G)(a.g,function(d){return d.id}),c=T5(a.l,"/pairing/get_lounge_token_batch");
U5(a.l,c,{screen_ids:b.join(",")},(0,g.z)(a.WC,a),(0,g.z)(a.VC,a))}},f6=function(a){var b=t4(F4());
b=(0,g.Zd)(b,function(c){return!c.uuid});
return Tpa(a,b)},i6=function(a,b){Fpa((0,g.G)(a.g,s4));
b&&G4()},k6=function(a,b){g.Q.call(this);
this.A=b;var c=g.$s("yt-remote-online-screen-ids")||"";c=c?c.split(","):[];for(var d={},e=this.A(),f=0,k=e.length;f<k;++f){var l=e[f].id;d[l]=g.ab(c,l)}this.g=d;this.u=a;this.l=this.o=NaN;this.i=null;j6("Initialized with "+g.Hg(this.g))},l6=function(a,b,c){var d=T5(a.u,"/pairing/get_screen_availability");
U5(a.u,d,{lounge_token:b.token},(0,g.z)(function(e){e=e.screens||[];for(var f=0,k=e.length;f<k;++f)if(e[f].loungeToken==b.token){c("online"==e[f].status);return}c(!1)},a),(0,g.z)(function(){c(!1)},a))},m6=function(a,b){a:if(l4(b)!=l4(a.g))var c=!1;
else{c=g.Sb(b);for(var d=0,e=c.length;d<e;++d)if(!a.g[c[d]]){c=!1;break a}c=!0}c||(j6("Updated online screens: "+g.Hg(a.g)),a.g=b,a.N("screenChange"));Vpa(a)},n6=function(a){isNaN(a.l)||g.Ip(a.l);
a.l=g.Gp((0,g.z)(a.Kr,a),0<a.o&&a.o<(0,g.C)()?2E4:1E4)},j6=function(a){Z5("OnlineScreenService",a)},o6=function(a){var b={};
(0,g.B)(a.A(),function(c){c.token?b[c.token]=c.id:this.Lb("Requesting availability of screen w/o lounge token.")});
return b},Vpa=function(a){a=g.Sb(g.Mb(a.g,function(b){return b}));
g.rb(a);a.length?g.Zs("yt-remote-online-screen-ids",a.join(","),60):g.at("yt-remote-online-screen-ids")},p6=function(a){c6.call(this,"ScreenService");
this.A=a;this.i=this.l=null;this.o=[];this.u={};Wpa(this)},r6=function(a,b,c,d,e,f){a.info("getAutomaticScreenByIds "+c+" / "+b);
c||(c=a.u[b]);var k=a.Ed();if(k=(c?y4(k,c):null)||y4(k,b)){k.uuid=b;var l=q6(a,k);l6(a.i,l,function(m){e(m?l:null)})}else c?Xpa(a,c,(0,g.z)(function(m){var n=q6(this,new q4({name:d,
screenId:c,loungeToken:m,dialId:b||""}));l6(this.i,n,function(p){e(p?n:null)})},a),f):e(null)},s6=function(a,b){for(var c=0,d=a.g.length;c<d;++c)if(a.g[c].name==b)return a.g[c];
return null},Xpa=function(a,b,c,d){a.info("requestLoungeToken_ for "+b);
var e={qb:{screen_ids:b},method:"POST",context:a,onSuccess:function(f,k){var l=k&&k.screens||[];l[0]&&l[0].screenId==b?c(l[0].loungeToken):d(Error("Missing lounge token in token response"))},
onError:function(){d(Error("Request screen lounge token failed"))}};
g.vq(T5(a.A,"/pairing/get_lounge_token_batch"),e)},t6=function(a){a.g=a.l.Ed();
var b=a.u,c={},d;for(d in b)c[b[d]]=d;b=0;for(d=a.g.length;b<d;++b){var e=a.g[b];e.uuid=c[e.id]||""}a.info("Updated manual screens: "+v4(a.g))},Wpa=function(a){u6(a);
a.l=new g6(a.A);a.l.subscribe("screenChange",(0,g.z)(a.fD,a));t6(a);a.o=t4(g.$s("yt-remote-automatic-screen-cache")||[]);u6(a);a.info("Initializing automatic screens: "+v4(a.o));a.i=new k6(a.A,(0,g.z)(a.Ed,a,!0));a.i.subscribe("screenChange",(0,g.z)(function(){this.N("onlineScreenChange")},a))},q6=function(a,b){var c=a.get(b.id);
c?(c.uuid=b.uuid,b=c):((c=y4(a.o,b.uuid))?(c.id=b.id,c.token=b.token,b=c):a.o.push(b),g.Zs("yt-remote-automatic-screen-cache",(0,g.G)(a.o,s4)));u6(a);a.u[b.uuid]=b.id;g.Zs("yt-remote-device-id-map",a.u,31536E3);return b},u6=function(a){a.u=g.$s("yt-remote-device-id-map")||{}},v6=function(a,b,c){g.Q.call(this);
this.P=c;this.F=a;this.i=b;this.l=null},w6=function(a,b){Z5(a.P,b)},y6=function(a,b){v6.call(this,a,b,"CastSession");
this.g=null;this.o=0;this.A=(0,g.z)(this.zM,this);this.u=(0,g.z)(this.jL,this);this.o=g.Gp((0,g.z)(function(){x6(this,null)},this),12E4)},Ypa=function(a){a.info("sendYoutubeMessage_: getMdxSessionStatus "+g.Hg(void 0));
var b={type:"getMdxSessionStatus"};a.g?a.g.sendMessage("urn:x-cast:com.google.youtube.mdx",b,g.Ia,(0,g.z)(function(){w6(this,"Failed to send message: getMdxSessionStatus.")},a)):w6(a,"Sending yt message without session: "+g.Hg(b))},x6=function(a,b){g.Ip(a.o);
if(b){if(a.info("onConnectedScreenId_: Received screenId: "+b),!a.l||a.l.id!=b){var c=(0,g.z)(a.Xm,a),d=(0,g.z)(a.Id,a);a.yv(b,c,d,5)}}else a.Id(Error("Waiting for session status timed out."))},z6=function(a,b,c){v6.call(this,a,b,"DialSession");
this.o=this.D=null;this.H="";this.M=c;this.u=null;this.B=g.Ia;this.A=NaN;this.I=(0,g.z)(this.CM,this);this.g=g.Ia},A6=function(a){a.g=a.F.NA(a.H,a.i.label,a.i.friendlyName,(0,g.z)(function(b){this.g=g.Ia;
this.Xm(b)},a),(0,g.z)(function(b){this.g=g.Ia;
this.Id(b)},a))},B6=function(a){var b={};
b.pairingCode=a.H;b.theme=a.M;if(a.u){var c=a.u.currentTime||0;b.v=a.u.videoId;b.t=c}J4()&&(b.env_useStageMdx=1);return g.Xg(b)},C6=function(a,b){v6.call(this,a,b,"ManualSession");
this.g=g.Gp((0,g.z)(this.bi,this,null),150)},D6=function(a,b,c,d){g.Q.call(this);
this.i=a;this.B=b||"233637DE";this.A=c||"cl";this.D=d||!1;this.g=null;this.u=!1;this.l=[];this.o=(0,g.z)(this.PJ,this)},E6=function(a,b){return b?g.Ya(a.l,function(c){return r4(b,c.label)},a):null},F6=function(a){Z5("Controller",a)},V5=function(a){window.chrome&&chrome.cast&&chrome.cast.logMessage&&chrome.cast.logMessage(a)},G6=function(a){return a.u||!!a.l.length||!!a.g},H6=function(a,b,c){b!=a.g&&(g.qf(a.g),(a.g=b)?(c?a.N("yt-remote-cast2-receiver-resumed",b.i):a.N("yt-remote-cast2-receiver-selected",
b.i),b.subscribe("sessionScreen",(0,g.z)(a.Ey,a,b)),b.l?a.N("yt-remote-cast2-session-change",b.l):c&&a.g.bi(null)):a.N("yt-remote-cast2-session-change",null))},I6=function(a){var b=a.i.MA(),c=a.g&&a.g.i;
a=(0,g.G)(b,function(d){c&&r4(d,c.label)&&(c=null);var e=d.uuid?d.uuid:d.id,f=E6(this,d);f?(f.label=e,f.friendlyName=d.name):(f=new chrome.cast.Receiver(e,d.name),f.receiverType=chrome.cast.ReceiverType.CUSTOM);return f},a);
c&&(c.receiverType!=chrome.cast.ReceiverType.CUSTOM&&(c=new chrome.cast.Receiver(c.label,c.friendlyName),c.receiverType=chrome.cast.ReceiverType.CUSTOM),a.push(c));return a},bqa=function(a,b,c,d,e,f,k){Zpa()?$pa(b,e,f,k)&&(K6(!0),window.chrome&&chrome.cast&&chrome.cast.isAvailable?L6(a,c):(window.__onGCastApiAvailable=function(l,m){l?L6(a,c):(M6("Failed to load cast API: "+m),N6(!1),K6(!1),g.at("yt-remote-cast-available"),g.at("yt-remote-cast-receiver"),O6(),c(!1))},d?g.Tp("https://www.gstatic.com/cv/js/sender/v1/cast_sender.js"):
0<=window.navigator.userAgent.indexOf("Android")&&0<=window.navigator.userAgent.indexOf("Chrome/")&&window.navigator.presentation?Jpa():!window.chrome||!window.navigator.presentation||0<=window.navigator.userAgent.indexOf("Edge")?O4():(Q4(),N4(aqa.map(Hpa))))):J6("Cannot initialize because not running Chrome")},O6=function(){J6("dispose");
var a=P6();a&&a.dispose();g.Ha("yt.mdx.remote.cloudview.instance_",null,void 0);Q6(!1);g.Op(R6);R6.length=0},S6=function(){return!!g.$s("yt-remote-cast-installed")},T6=function(){var a=g.$s("yt-remote-cast-receiver");
return a?a.friendlyName:null},U6=function(){J6("clearCurrentReceiver");
g.at("yt-remote-cast-receiver")},V6=function(){return S6()?P6()?P6().getCastSession():(M6("getCastSelector: Cast is not initialized."),null):(M6("getCastSelector: Cast API is not installed!"),null)},X6=function(){S6()?P6()?W6()?(J6("Requesting cast selector."),P6().requestSession()):(J6("Wait for cast API to be ready to request the session."),R6.push(g.Np("yt-remote-cast2-api-ready",X6))):M6("requestCastSelector: Cast is not initialized."):M6("requestCastSelector: Cast API is not installed!")},Y6=
function(a,b){W6()?P6().setConnectedScreenStatus(a,b):M6("setConnectedScreenStatus called before ready.")},Zpa=function(){var a=0<=g.Jb.search(/ (CrMo|Chrome|CriOS)\//);
return g.Jw||a},cqa=function(a,b){P6().init(a,b)},$pa=function(a,b,c,d){var e=!1;
P6()||(a=new D6(a,b,c,d),a.subscribe("yt-remote-cast2-availability-change",function(f){g.Zs("yt-remote-cast-available",f);o4("yt-remote-cast2-availability-change",f)}),a.subscribe("yt-remote-cast2-receiver-selected",function(f){J6("onReceiverSelected: "+f.friendlyName);
g.Zs("yt-remote-cast-receiver",f);o4("yt-remote-cast2-receiver-selected",f)}),a.subscribe("yt-remote-cast2-receiver-resumed",function(f){J6("onReceiverResumed: "+f.friendlyName);
g.Zs("yt-remote-cast-receiver",f)}),a.subscribe("yt-remote-cast2-session-change",function(f){J6("onSessionChange: "+u4(f));
f||g.at("yt-remote-cast-receiver");o4("yt-remote-cast2-session-change",f)}),g.Ha("yt.mdx.remote.cloudview.instance_",a,void 0),e=!0);
J6("cloudview.createSingleton_: "+e);return e},P6=function(){return g.x("yt.mdx.remote.cloudview.instance_")},L6=function(a,b){N6(!0);
K6(!1);cqa(a,function(c){c?(Q6(!0),g.Qp("yt-remote-cast2-api-ready")):(M6("Failed to initialize cast API."),N6(!1),g.at("yt-remote-cast-available"),g.at("yt-remote-cast-receiver"),O6());b(c)})},J6=function(a){Z5("cloudview",a)},M6=function(a){Z5("cloudview",a)},N6=function(a){J6("setCastInstalled_ "+a);
g.Zs("yt-remote-cast-installed",a)},W6=function(){return!!g.x("yt.mdx.remote.cloudview.apiReady_")},Q6=function(a){J6("setApiReady_ "+a);
g.Ha("yt.mdx.remote.cloudview.apiReady_",a,void 0)},K6=function(a){g.Ha("yt.mdx.remote.cloudview.initializing_",a,void 0)},Z6=function(a){this.index=-1;
this.videoId=this.listId="";this.volume=this.playerState=-1;this.muted=!1;this.audioTrackId=null;this.A=this.B=0;this.g=null;this.hasNext=this.Ge=!1;this.F=this.D=this.i=this.o=0;this.l=NaN;this.u=!1;this.reset(a)},$6=function(a){a.audioTrackId=null;
a.g=null;a.playerState=-1;a.Ge=!1;a.hasNext=!1;a.B=0;a.A=(0,g.C)();a.o=0;a.i=0;a.D=0;a.F=0;a.l=NaN;a.u=!1},a7=function(a){return 1==a.playerState?((0,g.C)()-a.A)/1E3:0},b7=function(a,b){a.B=b;
a.A=(0,g.C)()},c7=function(a){switch(a.playerState){case 1:case 1081:return((0,g.C)()-a.A)/1E3+a.B;
case -1E3:return 0}return a.B},d7=function(a,b,c){var d=a.videoId;
a.videoId=b;a.index=c;b!=d&&$6(a)},e7=function(a){var b={};
b.index=a.index;b.listId=a.listId;b.videoId=a.videoId;b.playerState=a.playerState;b.volume=a.volume;b.muted=a.muted;b.audioTrackId=a.audioTrackId;b.trackData=g.dc(a.g);b.hasPrevious=a.Ge;b.hasNext=a.hasNext;b.playerTime=a.B;b.playerTimeAt=a.A;b.seekableStart=a.o;b.seekableEnd=a.i;b.duration=a.D;b.loadedTime=a.F;b.liveIngestionTime=a.l;return b},h7=function(a,b){g.Q.call(this);
this.g=0;this.o=a;this.A=[];this.u=new n4;this.l=this.i=null;this.F=(0,g.z)(this.JH,this);this.B=(0,g.z)(this.ik,this);this.D=(0,g.z)(this.IH,this);this.H=(0,g.z)(this.VH,this);var c=0;a?(c=a.getProxyState(),3!=c&&(a.subscribe("proxyStateChange",this.Os,this),f7(this))):c=3;0!=c&&(b?this.Os(c):g.Gp((0,g.z)(function(){this.Os(c)},this),0));
var d=V6();d&&g7(this,d);this.subscribe("yt-remote-cast2-session-change",this.H)},i7=function(a){return new Z6(a.o.getPlayerContextData())},f7=function(a){(0,g.B)("nowAutoplaying autoplayDismissed remotePlayerChange remoteQueueChange autoplayModeChange autoplayUpNext previousNextChange".split(" "),function(b){this.A.push(this.o.subscribe(b,g.Sa(this.MJ,b),this))},a)},j7=function(a){(0,g.B)(a.A,function(b){this.o.unsubscribeByKey(b)},a);
a.A.length=0},k7=function(a,b){var c=a.u;
50>c.g.length+c.i.length&&a.u.i.push(b)},m7=function(a,b,c){var d=i7(a);
b7(d,c);-1E3!=d.playerState&&(d.playerState=b);l7(a,d)},n7=function(a,b,c){a.o.sendMessage(b,c)},l7=function(a,b){j7(a);
a.o.setPlayerContextData(e7(b));f7(a)},g7=function(a,b){a.l&&(a.l.removeUpdateListener(a.F),a.l.removeMediaListener(a.B),a.ik(null));
a.l=b;a.l&&(Z5("CP","Setting cast session: "+a.l.sessionId),a.l.addUpdateListener(a.F),a.l.addMediaListener(a.B),a.l.media.length&&a.ik(a.l.media[0]))},o7=function(a){var b=a.i.media,c=a.i.customData;
if(b&&c){var d=i7(a);b.contentId!=d.videoId&&Z5("CP","Cast changing video to: "+b.contentId);d.videoId=b.contentId;d.playerState=c.playerState;b7(d,a.i.getEstimatedTime());l7(a,d)}else Z5("CP","No cast media video. Ignoring state update.")},p7=function(a,b,c){return(0,g.z)(function(d){this.Lb("Failed to "+b+" with cast v2 channel. Error code: "+d.code);
d.code!=chrome.cast.ErrorCode.TIMEOUT&&(this.Lb("Retrying "+b+" using MDx browser channel."),n7(this,b,c))},a)},q7=function(a,b,c){g.Q.call(this);
this.u=NaN;this.M=!1;this.H=this.F=this.I=this.P=NaN;this.O=[];this.o=this.B=this.l=this.Qa=this.g=null;this.na=a;this.O.push(g.vr(window,"beforeunload",(0,g.z)(this.PC,this)));this.i=[];this.Qa=new Z6;this.V=b.id;this.g=dqa(this,c);this.g.subscribe("handlerOpened",this.NH,this);this.g.subscribe("handlerClosed",this.KH,this);this.g.subscribe("handlerError",this.LH,this);this.g.subscribe("handlerMessage",this.MH,this);Opa(this.g,b.token);this.subscribe("remoteQueueChange",function(){var d=this.Qa.videoId;
g.bt()&&g.Zs("yt-remote-session-video-id",d)},this)},r7=function(a){Z5("conn",a)},dqa=function(a,b){return new P5(T5(a.na,"/bc"),b)},s7=function(a,b){a.N("proxyStateChange",b)},eqa=function(a){a.u=g.Gp((0,g.z)(function(){r7("Connecting timeout");
this.A(1)},a),2E4)},t7=function(a){g.Ip(a.u);
a.u=NaN},u7=function(a){g.Ip(a.P);
a.P=NaN},fqa=function(a){v7(a);
a.I=g.Gp((0,g.z)(function(){w7(this,"getNowPlaying")},a),2E4)},v7=function(a){g.Ip(a.I);
a.I=NaN},y7=function(a,b){b&&(t7(a),u7(a));
b==(R5(a.g)&&isNaN(a.u))?b&&(s7(a,1),w7(a,"getSubtitlesTrack")):b?(a.R()&&a.Qa.reset(),s7(a,1),w7(a,"getNowPlaying"),x7(a)):a.A(1)},gqa=function(a,b){var c=b.params.videoId;
delete b.params.videoId;c==a.Qa.videoId&&(g.Yb(b.params)?a.Qa.g=null:a.Qa.g=b.params,a.N("remotePlayerChange"))},z7=function(a,b){var c=b.params.videoId||b.params.video_id,d=parseInt(b.params.currentIndex,10);
a.Qa.listId=b.params.listId||a.Qa.listId;d7(a.Qa,c,d);a.N("remoteQueueChange")},hqa=function(a,b){b.params=b.params||{};
z7(a,b);A7(a,b);a.N("autoplayDismissed")},A7=function(a,b){var c=parseInt(b.params.currentTime||b.params.current_time,10);
b7(a.Qa,isNaN(c)?0:c);c=parseInt(b.params.state,10);c=isNaN(c)?-1:c;-1==c&&-1E3==a.Qa.playerState&&(c=-1E3);a.Qa.playerState=c;c=Number(b.params.loadedTime);a.Qa.F=isNaN(c)?0:c;c=Number(b.params.duration);a.Qa.D=isNaN(c)?0:c;c=a.Qa;var d=Number(b.params.liveIngestionTime);c.l=d;c.u=isNaN(d)?!1:!0;c=a.Qa;d=Number(b.params.seekableStartTime);var e=Number(b.params.seekableEndTime);c.o=isNaN(d)?0:d;c.i=isNaN(e)?0:e;1==a.Qa.playerState?fqa(a):v7(a);a.N("remotePlayerChange")},iqa=function(a,b){if(-1E3!=
a.Qa.playerState){var c=1085;
switch(parseInt(b.params.adState,10)){case 1:c=1081;break;case 2:c=1084;break;case 0:c=1083}a.Qa.playerState=c;c=parseInt(b.params.currentTime,10);b7(a.Qa,isNaN(c)?0:c);a.N("remotePlayerChange")}},jqa=function(a,b){var c="true"==b.params.muted;
a.Qa.volume=parseInt(b.params.volume,10);a.Qa.muted=c;a.N("remotePlayerChange")},kqa=function(a,b){a.B=b.params.videoId;
a.N("nowAutoplaying",parseInt(b.params.timeout,10))},lqa=function(a,b){var c="true"==b.params.hasNext;
a.Qa.Ge="true"==b.params.hasPrevious;a.Qa.hasNext=c;a.N("previousNextChange")},x7=function(a){g.Ip(a.H);
a.H=g.Gp((0,g.z)(a.A,a,1),864E5)},w7=function(a,b,c){c?r7("Sending: action="+b+", params="+g.Hg(c)):r7("Sending: action="+b);
a.g.sendMessage(b,c)},B7=function(a){c6.call(this,"ScreenServiceProxy");
this.Ic=a;this.i=[];this.i.push(this.Ic.$_s("screenChange",(0,g.z)(this.xM,this)));this.i.push(this.Ic.$_s("onlineScreenChange",(0,g.z)(this.qJ,this)))},qqa=function(a){var b={device:"Desktop",
app:"youtube-desktop"};b=g.yp("MDX_CONFIG")||b;Dpa();D4();C7||(C7=new S5(b?b.loungeApiHost:void 0),J4()&&(C7.g="/api/loungedev"));D7||(D7=g.x("yt.mdx.remote.deferredProxies_")||[],g.Ha("yt.mdx.remote.deferredProxies_",D7,void 0));mqa();var c=E7();if(!c){var d=new p6(C7);g.Ha("yt.mdx.remote.screenService_",d,void 0);c=E7();var e=!1,f=void 0,k=void 0,l=!1;b&&(e=!!b.loadCastApiSetupScript,f=b.appId,k=b.theme,l=!!b.disableDial);bqa(a,d,function(m){m?F7()&&Y6(F7(),"YouTube TV"):d.subscribe("onlineScreenChange",
function(){o4("yt-remote-receiver-availability-change")})},e,f,k,l)}b&&!g.x("yt.mdx.remote.initialized_")&&(g.Ha("yt.mdx.remote.initialized_",!0,void 0),G7("Initializing: "+g.Hg(b)),H7.push(g.Np("yt-remote-cast2-availability-change",function(){o4("yt-remote-receiver-availability-change")})),H7.push(g.Np("yt-remote-cast2-receiver-selected",function(){I7(null);
o4("yt-remote-auto-connect","cast-selector-receiver")})),H7.push(g.Np("yt-remote-cast2-receiver-resumed",function(){o4("yt-remote-receiver-resumed","cast-selector-receiver")})),H7.push(g.Np("yt-remote-cast2-session-change",nqa)),H7.push(g.Np("yt-remote-connection-change",function(m){m?Y6(F7(),"YouTube TV"):J7()||(Y6(null,null),U6())})),a=K7(),b.isAuto&&(a.id+="#dial"),g.mq("desktop_enable_autoplay")&&(a.capabilities=["atp"]),a.name=b.device,a.app=b.app,(k=b.theme)&&(a.theme=k),G7(" -- with channel params: "+
g.Hg(a)),oqa(a),c.start(),F7()||pqa())},rqa=function(){var a=L7();
S6()&&g.$s("yt-remote-cast-available")&&a.push({key:"cast-selector-receiver",name:"Cast..."});return a},L7=function(){var a=E7().Ic.$_gos();
var b=M7();b&&N7()&&(x4(a,b)||a.push(b));return Cpa(a)},O7=function(){var a=sqa();
!a&&S6()&&T6()&&(a={key:"cast-selector-receiver",name:T6()});return a},sqa=function(){var a=L7(),b=M7();
b||(b=J7());return g.Ya(a,function(c){return b&&r4(b,c.key)?!0:!1})},M7=function(){var a=F7();
if(!a)return null;var b=E7().Ed();return y4(b,a)},nqa=function(a){G7("remote.onCastSessionChange_: "+u4(a));
if(a){var b=M7();b&&b.id==a.id?Y6(b.id,"YouTube TV"):(b&&P7(),Q7(a,1))}else N7()&&P7()},P7=function(){W6()?P6().stopSession():M6("stopSession called before API ready.");
var a=N7();a&&(a.disconnect(1),R7(null))},S7=function(){var a=N7();
return!!a&&3!=a.getProxyState()},G7=function(a){Z5("remote",a)},E7=function(){if(!T7){var a=g.x("yt.mdx.remote.screenService_");
T7=a?new B7(a):null}return T7},F7=function(){return g.x("yt.mdx.remote.currentScreenId_")},U7=function(a){g.Ha("yt.mdx.remote.currentScreenId_",a,void 0)},V7=function(){return g.x("yt.mdx.remote.connectData_")},I7=function(a){g.Ha("yt.mdx.remote.connectData_",a,void 0)},N7=function(){return g.x("yt.mdx.remote.connection_")},R7=function(a){var b=N7();
I7(null);a||U7("");g.Ha("yt.mdx.remote.connection_",a,void 0);D7&&((0,g.B)(D7,function(c){c(a)}),D7.length=0);
b&&!a?o4("yt-remote-connection-change",!1):!b&&a&&o4("yt-remote-connection-change",!0)},J7=function(){var a=g.bt();
if(!a)return null;var b=E7().Ed();return y4(b,a)},Q7=function(a,b){M7()&&M7();
U7(a.id);var c=new q7(C7,a,K7());c.connect(b,V7());c.subscribe("beforeDisconnect",function(d){o4("yt-remote-before-disconnect",d)});
c.subscribe("beforeDispose",function(){N7()&&R7(null)});
R7(c)},pqa=function(){var a=J7();
a?(G7("Resume connection to: "+u4(a)),Q7(a,0)):(H4(),U6(),G7("Skipping connecting because no session screen found."))},mqa=function(){var a=K7();
if(g.Yb(a)){a=C4();var b=g.$s("yt-remote-session-name")||"",c=g.$s("yt-remote-session-app")||"";a={device:"REMOTE_CONTROL",id:a,name:b,app:c,mdxVersion:3};g.Ha("yt.mdx.remote.channelParams_",a,void 0)}},K7=function(){return g.x("yt.mdx.remote.channelParams_")||{}},oqa=function(a){a?(g.Zs("yt-remote-session-app",a.app),g.Zs("yt-remote-session-name",a.name)):(g.at("yt-remote-session-app"),g.at("yt-remote-session-name"));
g.Ha("yt.mdx.remote.channelParams_",a,void 0)},W7=function(a,b,c){g.H.call(this);
this.u=a;this.i=b;this.l=new g.Ir(this);g.I(this,this.l);this.l.K(b,"onCaptionsTrackListChanged",this.HI);this.l.K(b,"captionschanged",this.HH);this.l.K(b,"captionssettingschanged",this.Zz);this.l.K(b,"videoplayerreset",this.Ym);this.l.K(b,"mdxautoplaycancel",this.XB);this.O=this.l.K(b,"onVolumeChange",this.my);this.D=!1;this.g=c;c.subscribe("proxyStateChange",this.Ay,this);c.subscribe("remotePlayerChange",this.kk,this);c.subscribe("remoteQueueChange",this.Ym,this);c.subscribe("autoplayUpNext",this.Zx,
this);c.subscribe("previousNextChange",this.wy,this);c.subscribe("nowAutoplaying",this.ry,this);c.subscribe("autoplayDismissed",this.Yx,this);this.suggestion=null;this.F=new g.BC(64);this.o=new g.N(this.Xz,500,this);g.I(this,this.o);this.A=new g.N(this.Yz,1E3,this);g.I(this,this.A);this.I=new R4(this.gM,0,this);g.I(this,this.I);this.B={};this.P=new g.N(this.yA,1E3,this);g.I(this,this.P);this.H=new g.wl(this.nF,1E3,this);g.I(this,this.H);this.M=g.Ia;this.Zz();this.Ym();this.kk()},X7=function(a,b){a.u.pd(b,
a.i.getVideoData().lengthSeconds)},Z7=function(a){X7(a,0);
a.o.stop();Y7(a,new g.BC(64))},a8=function(a,b){if($7(a)&&!a.D){var c=null;
b&&(c={style:a.i.getSubtitlesUserSettings()},g.fc(c,b));a.g.Nz(a.i.getVideoData(1).videoId,c);a.B=i7(a.g).g}},b8=function(a,b){var c=a.i.getPlaylist();
if(c){var d=c.Sa;var e=c.listId.toString()}c=a.i.getVideoData(1);a.g.playVideo(c.videoId,b,d,e,c.playerParams,c.eg,k4(c));Y7(a,new g.BC(1))},c8=function(a,b){if(b){var c=a.i.getOption("captions","tracklist",{SP:1});
c&&c.length?(a.i.setOption("captions","track",b),a.D=!1):(a.i.loadModule("captions"),a.D=!0)}else a.i.setOption("captions","track",{})},$7=function(a){return i7(a.g).videoId==a.i.getVideoData(1).videoId},Y7=function(a,b){a.A.stop();
var c=a.F;if(!g.HC(c,b)){var d=g.V(b,2);d!=g.V(a.F,2)&&g.pJ(a.i,d);a.F=b;d8(a.u,c,b)}},f8=function(a){g.U.call(this,{C:"div",
G:"ytp-remote",J:[{C:"div",G:"ytp-remote-display-status",J:[{C:"div",G:"ytp-remote-display-status-icon",J:[g.DO()]},{C:"div",G:"ytp-remote-display-status-text",U:"{{statustext}}"}]}]});this.l=new g.nP(this,250);g.I(this,this.l);this.o=a;this.K(a,"presentingplayerstatechange",this.u);e8(this,g.lJ(a))},e8=function(a,b){if(3==a.o.getPresentingPlayerType()){var c={RECEIVER_NAME:a.o.getOption("remote","currentReceiver").name};
c=g.V(b,128)?g.CM("Error on $RECEIVER_NAME",c):g.IC(b)||g.V(b,4)?g.CM("Playing on $RECEIVER_NAME",c):g.CM("Connected to $RECEIVER_NAME",c);a.updateValue("statustext",c);a.l.show()}else a.l.hide()},g8=function(a,b){g.XS.call(this,"Play on",0,a,b);
this.l=a;this.F={};this.K(a,"onMdxReceiversChange",this.I);this.K(a,"presentingplayerstatechange",this.I);this.I()},h8=function(a){g.QJ.call(this,a);
this.i={key:w4(),name:"This computer"};this.o=null;this.u=[];this.B=this.g=null;this.A=[this.i];this.l=this.i;this.Vj=new g.BC(64);this.D=0;this.nm=-1;if(!g.Hy(g.W(this.player))){a=this.player;var b=g.$B(a);b&&(b=b.Im())&&(b=new g8(a,b),g.I(this,b));b=new f8(a);g.I(this,b);g.CJ(a,b.element,4)}},d8=function(a,b,c){a.Vj=c;
a.player.N("presentingplayerstatechange",new g.MC(c,b))},i8=function(a,b){if(b.key!=a.l.key)if(b.key==a.i.key)P7();
else{a.l=b;var c=a.player.getPlaylistId();var d=a.player.getVideoData(1);var e=d.videoId;if(c||e){var f=a.player.getPlaylist();if(f){var k=[];for(var l=0;l<f.getLength();l++)k[l]=f.oa(l).videoId}else k=[e];f=a.player.getCurrentTime(1);c={videoIds:k,listId:c,videoId:e,playerParams:d.playerParams,clickTrackingParams:d.eg,index:Math.max(a.player.getPlaylistIndex(),0),currentTime:0==f?void 0:f};(d=k4(d))&&(c.locationInfo=d);d=c}else d=null;G7("Connecting to: "+g.Hg(b));"cast-selector-receiver"==b.key?
(I7(d||null),W6()?P6().setLaunchParams(d||null):M6("setLaunchParams called before ready.")):!d&&S7()&&F7()==b.key?o4("yt-remote-connection-change",!0):(P7(),I7(d||null),d=E7().Ed(),(d=y4(d,b.key))&&Q7(d,1))}},rpa=/^https?$/i,tqa=["POST",
"PUT"];g.A(i4,g.Qf);g.h=i4.prototype;
g.h.send=function(a,b,c,d){if(this.g)throw Error("[goog.net.XhrIo] Object is active with another request="+this.F+"; newUri="+a);b=b?b.toUpperCase():"GET";this.F=a;this.l="";this.u=0;this.aa=b;this.O=!1;this.i=!0;this.g=this.M?a4(this.M):a4(g.bY);this.P=this.M?this.M.getOptions():g.bY.getOptions();this.g.onreadystatechange=(0,g.z)(this.Hv,this);try{Y3(b4(this,"Opening Xhr")),this.V=!0,this.g.open(b,String(a),!0),this.V=!1}catch(f){Y3(b4(this,"Error opening Xhr: "+f.message));f4(this,f);return}a=c||
"";var e=this.headers.clone();d&&opa(d,function(f,k){e.set(k,f)});
d=g.Ya(e.Dd(),ppa);c=g.w.FormData&&a instanceof g.w.FormData;!g.ab(tqa,b)||d||c||e.set("Content-Type","application/x-www-form-urlencoded;charset=utf-8");e.forEach(function(f,k){this.g.setRequestHeader(k,f)},this);
this.Y&&(this.g.responseType=this.Y);"withCredentials"in this.g&&this.g.withCredentials!==this.R&&(this.g.withCredentials=this.R);try{c4(this),0<this.A&&(this.I=qpa(this.g),Y3(b4(this,"Will abort after "+this.A+"ms if incomplete, xhr2 "+this.I)),this.I?(this.g.timeout=this.A,this.g.ontimeout=(0,g.z)(this.Iv,this)):this.B=g.Dg(this.Iv,this.A,this)),Y3(b4(this,"Sending request")),this.D=!0,this.g.send(a),this.D=!1}catch(f){Y3(b4(this,"Send error: "+f.message)),f4(this,f)}};
g.h.Iv=function(){"undefined"!=typeof g.FX&&this.g&&(this.l="Timed out after "+this.A+"ms, aborting",this.u=8,b4(this,this.l),this.dispatchEvent("timeout"),this.abort(8))};
g.h.abort=function(a){this.g&&this.i&&(b4(this,"Aborting"),this.i=!1,this.o=!0,this.g.abort(),this.o=!1,this.u=a||7,this.dispatchEvent("complete"),this.dispatchEvent("abort"),e4(this))};
g.h.T=function(){this.g&&(this.i&&(this.i=!1,this.o=!0,this.g.abort(),this.o=!1),e4(this,!0));i4.Ga.T.call(this)};
g.h.Hv=function(){this.ea()||(this.V||this.D||this.o?h4(this):this.OJ())};
g.h.OJ=function(){h4(this)};
g.h.isActive=function(){return!!this.g};
g.h.getStatus=function(){try{return 2<g4(this)?this.g.status:-1}catch(a){return-1}};
g.h.getLastError=function(){return g.v(this.l)?this.l:String(this.l)};
var f5={"\x00":"\\0","\b":"\\b","\f":"\\f","\n":"\\n","\r":"\\r","\t":"\\t","\x0B":"\\x0B",'"':'\\"',"\\":"\\\\","<":"<"},e5={"'":"\\'"},uqa={};g.h=n4.prototype;g.h.isEmpty=function(){return 0==this.g.length&&0==this.i.length};
g.h.clear=function(){this.g=[];this.i=[]};
g.h.contains=function(a){return g.ab(this.g,a)||g.ab(this.i,a)};
g.h.remove=function(a){var b=this.g;var c=(0,g.Zla)(b,a);0<=c?(g.cb(b,c),b=!0):b=!1;return b||g.db(this.i,a)};
g.h.zc=function(){for(var a=[],b=this.g.length-1;0<=b;--b)a.push(this.g[b]);var c=this.i.length;for(b=0;b<c;++b)a.push(this.i[b]);return a};
var Apa={WM:"atp",hP:"ska",WO:"que",vO:"mus",gP:"sus",MN:"dsp",dP:"seq"};p4.prototype.Sf=function(){var a=new p4({id:this.id,name:this.name,app:this.app,type:this.type,user:this.username,userAvatarUri:this.avatar,obfuscatedGaiaId:this.obfuscatedGaiaId,theme:this.theme,capabilities:Array.from(this.capabilities.values()).join(","),experiments:Array.from(this.experiments.values()).join(",")});a.l=this.l;a.i=this.i;a.g=this.g};
var I4,B4="",P4=K4("loadGamesSDK")?"/cast_game_sender.js":"/cast_sender.js",Ipa=K4("loadCastFramework")||K4("loadCastApplicationFramework"),aqa=["pkedcjkdefgpdelpbcmbmeomcjbeemfm","enhhojjnijigcajfphajepfemndkmdlo"];g.A(R4,g.H);g.h=R4.prototype;g.h.LC=function(a){this.o=arguments;this.g=!1;this.za?this.l=(0,g.C)()+this.Tc:this.za=g.Dg(this.u,this.Tc)};
g.h.stop=function(){this.za&&(g.w.clearTimeout(this.za),this.za=null);this.l=null;this.g=!1;this.o=[]};
g.h.pause=function(){++this.i};
g.h.resume=function(){this.i&&(--this.i,!this.i&&this.g&&(this.g=!1,this.A.apply(null,this.o)))};
g.h.T=function(){this.stop();R4.Ga.T.call(this)};
g.h.MC=function(){this.l?(this.za=g.Dg(this.u,this.l-(0,g.C)()),this.l=null):(this.za=null,this.i?this.g=!0:(this.g=!1,this.A.apply(null,this.o)))};S4.prototype.stringify=function(a){return g.w.JSON.stringify(a,void 0)};
S4.prototype.parse=function(a){return g.w.JSON.parse(a,void 0)};g.h=T4.prototype;g.h.Qg=null;g.h.se=!1;g.h.Ii=null;g.h.Ks=null;g.h.si=null;g.h.Ph=null;g.h.Zf=null;g.h.vg=null;g.h.kh=null;g.h.tc=null;g.h.Kk=0;g.h.we=null;g.h.Wn=null;g.h.ag=null;g.h.Aj=-1;g.h.zz=!0;g.h.Gg=!1;g.h.Cp=0;g.h.mn=null;var $4={},Y4={};g.h=T4.prototype;g.h.setTimeout=function(a){this.o=a};
g.h.uL=function(a){a=a.target;var b=this.mn;b&&3==g4(a)?b.wj():this.IA(a)};
g.h.IA=function(a){try{if(a==this.tc)a:{var b=g4(this.tc),c=this.tc.u,d=this.tc.getStatus();if(g.Nd&&!g.Ec(10)||g.Pd&&!g.Dc("420+")){if(4>b)break a}else if(3>b||3==b&&!g.yh&&!j4(this.tc))break a;this.Gg||4!=b||7==c||(8==c||0>=d?this.g.ne(3):this.g.ne(2));j5(this);var e=this.tc.getStatus();this.Aj=e;var f=j4(this.tc);(this.se=200==e)?(4==b&&b5(this),this.u?(d5(this,b,f),g.yh&&this.se&&3==b&&(this.ba.da(this.i,"tick",this.qL),this.i.start())):a5(this,f),this.se&&!this.Gg&&(4==b?this.g.Wm(this):(this.se=
!1,X4(this)))):(400==e&&0<f.indexOf("Unknown SID")?(this.ag=3,Z4(13)):(this.ag=0,Z4(14)),b5(this),c5(this))}}catch(k){this.tc&&j4(this.tc)}finally{}};
g.h.qL=function(){var a=g4(this.tc),b=j4(this.tc);this.Kk<b.length&&(j5(this),d5(this,a,b),this.se&&4!=a&&X4(this))};
g.h.OK=function(a){i5((0,g.z)(this.NK,this,a),0)};
g.h.NK=function(a){this.Gg||(j5(this),a5(this,a),X4(this))};
g.h.Hy=function(a){i5((0,g.z)(this.MK,this,a),0)};
g.h.MK=function(a){this.Gg||(b5(this),this.se=a,this.g.Wm(this),this.g.ne(4))};
g.h.cancel=function(){this.Gg=!0;b5(this)};
g.h.YK=function(){this.Ii=null;var a=(0,g.C)();0<=a-this.Ks?(2!=this.Ph&&this.g.ne(3),b5(this),this.ag=2,Z4(18),c5(this)):h5(this,this.Ks-a)};
g.h.getLastError=function(){return this.ag};g.h=n5.prototype;g.h.Ap=null;g.h.zd=null;g.h.nn=!1;g.h.Gv=null;g.h.Il=null;g.h.nq=null;g.h.Bp=null;g.h.Ud=null;g.h.sf=-1;g.h.zj=null;g.h.Ti=null;g.h.connect=function(a){this.Bp=a;a=o5(this.g,null,this.Bp);Z4(3);this.Gv=(0,g.C)();var b=this.g.D;null!=b?(this.zj=b[0],(this.Ti=b[1])?(this.Ud=1,p5(this)):(this.Ud=2,r5(this))):($3(a,"MODE","init"),this.zd=new T4(this,void 0,void 0,void 0),this.zd.Qg=this.Ap,W4(this.zd,a,!1,null,!0),this.Ud=0)};
g.h.YB=function(a){if(a)this.Ud=2,r5(this);else{Z4(4);var b=this.g;b.Ee=b.Rf.sf;L5(b,9)}a&&this.ne(2)};
g.h.Vo=function(a){return this.g.Vo(a)};
g.h.abort=function(){this.zd&&(this.zd.cancel(),this.zd=null);this.sf=-1};
g.h.Fv=function(){return!1};
g.h.By=function(a,b){this.sf=a.Aj;if(0==this.Ud)if(b){try{var c=this.i.parse(b)}catch(d){c=this.g;c.Ee=this.sf;L5(c,2);return}this.zj=c[0];this.Ti=c[1]}else c=this.g,c.Ee=this.sf,L5(c,2);else if(2==this.Ud)if(this.nn)Z4(7),this.nq=(0,g.C)();else if("11111"==b){if(Z4(6),this.nn=!0,this.Il=(0,g.C)(),c=this.Il-this.Gv,!g.Nd||g.Ec(10)||500>c)this.sf=200,this.zd.cancel(),Z4(12),q5(this.g,this,!0)}else Z4(8),this.Il=this.nq=(0,g.C)(),this.nn=!1};
g.h.Wm=function(){this.sf=this.zd.Aj;if(this.zd.se)0==this.Ud?this.Ti?(this.Ud=1,p5(this)):(this.Ud=2,r5(this)):2==this.Ud&&((!g.Nd||g.Ec(10)?!this.nn:200>this.nq-this.Il)?(Z4(11),q5(this.g,this,!1)):(Z4(12),q5(this.g,this,!0)));else{0==this.Ud?Z4(9):2==this.Ud&&Z4(10);var a=this.g;this.zd.getLastError();a.Ee=this.sf;L5(a,2)}};
g.h.Bk=function(){return this.g.Bk()};
g.h.isActive=function(){return this.g.isActive()};
g.h.ne=function(a){this.g.ne(a)};g.h=s5.prototype;g.h.gj=null;g.h.wd=null;g.h.Sb=null;g.h.zp=null;g.h.Kl=null;g.h.du=null;g.h.Tl=null;g.h.gk=0;g.h.ZG=0;g.h.Sc=null;g.h.Wf=null;g.h.df=null;g.h.Lg=null;g.h.Rf=null;g.h.Un=null;g.h.Zh=-1;g.h.lw=-1;g.h.Ee=-1;g.h.Kh=0;g.h.Eh=0;g.h.Hg=8;var M5=new g.Qf;g.A(t5,g.sf);g.A(u5,g.sf);g.A(v5,g.sf);g.h=s5.prototype;g.h.connect=function(a,b,c,d,e){Z4(0);this.zp=b;this.gj=c||{};d&&g.Ea(e)&&(this.gj.OSID=d,this.gj.OAID=e);this.A?(i5((0,g.z)(this.uu,this,a),100),B5(this)):this.uu(a)};
g.h.uu=function(a){this.Rf=new n5(this);this.Rf.Ap=null;this.Rf.i=this.u;this.Rf.connect(a)};
g.h.Fv=function(){return 0==this.g};
g.h.Gy=function(a){this.Wf=null;G5(this,a)};
g.h.Fy=function(){this.df=null;this.Sb=new T4(this,this.l,"rpc",this.B);this.Sb.Qg=null;this.Sb.Cp=0;var a=this.du.clone();g.Vm(a,"RID","rpc");g.Vm(a,"SID",this.l);g.Vm(a,"CI",this.Un?"0":"1");g.Vm(a,"AID",this.Zh);x5(this,a);if(!g.Nd||g.Ec(10))g.Vm(a,"TYPE","xmlhttp"),W4(this.Sb,a,!0,this.Tl,!1);else{g.Vm(a,"TYPE","html");var b=this.Sb,c=!!this.Tl;b.Ph=3;b.Zf=Z3(a.clone());g5(b,c)}};
g.h.By=function(a,b){if(0!=this.g&&(this.Sb==a||this.wd==a))if(this.Ee=a.Aj,this.wd==a&&3==this.g)if(7<this.Hg){try{var c=this.u.parse(b)}catch(f){c=null}if(g.Ma(c)&&3==c.length)if(0==c[0])a:{if(!this.df){if(this.Sb)if(this.Sb.si+3E3<this.wd.si)C5(this),this.Sb.cancel(),this.Sb=null;else break a;J5(this);Z4(19)}}else this.lw=c[1],0<this.lw-this.Zh&&37500>c[2]&&this.Un&&0==this.Eh&&!this.Lg&&(this.Lg=i5((0,g.z)(this.DH,this),6E3));else L5(this,11)}else b!=uqa.rN.g&&L5(this,11);else if(this.Sb==a&&
C5(this),!g.xb(b)){c=this.u.parse(b);g.Ma(c);for(var d=0;d<c.length;d++){var e=c[d];this.Zh=e[0];e=e[1];2==this.g?"c"==e[0]?(this.l=e[1],this.Tl=e[2],e=e[3],null!=e?this.Hg=e:this.Hg=6,this.g=3,this.Sc&&this.Sc.nu(),this.du=o5(this,this.Bk()?this.Tl:null,this.zp),H5(this)):"stop"==e[0]&&L5(this,7):3==this.g&&("stop"==e[0]?L5(this,7):"noop"!=e[0]&&this.Sc&&this.Sc.mu(e),this.Eh=0)}}};
g.h.DH=function(){null!=this.Lg&&(this.Lg=null,this.Sb.cancel(),this.Sb=null,J5(this),Z4(20))};
g.h.Wm=function(a){if(this.Sb==a){C5(this);this.Sb=null;var b=2}else if(this.wd==a)this.wd=null,b=1;else return;this.Ee=a.Aj;if(0!=this.g)if(a.se)1==b?(b=(0,g.C)()-a.si,M5.dispatchEvent(new u5(M5,a.kh?a.kh.length:0,b,this.Kh)),A5(this),this.o.length=0):H5(this);else{var c=a.getLastError(),d;if(!(d=3==c||7==c||0==c&&0<this.Ee)){if(d=1==b)this.wd||this.Wf||1==this.g||2<=this.Kh?d=!1:(this.Wf=i5((0,g.z)(this.Gy,this,a),I5(this,this.Kh)),this.Kh++,d=!0);d=!(d||2==b&&J5(this))}if(d)switch(c){case 1:L5(this,
5);break;case 4:L5(this,10);break;case 3:L5(this,6);break;case 7:L5(this,12);break;default:L5(this,2)}}};
g.h.pC=function(a){if(!g.ab(arguments,this.g))throw Error("Unexpected channel state: "+this.g);};
g.h.XL=function(a){a?Z4(2):(Z4(1),K5(this,8))};
g.h.Vo=function(a){if(a)throw Error("Can't create secondary domain capable XhrIo object.");a=new i4;a.R=!1;return a};
g.h.isActive=function(){return!!this.Sc&&this.Sc.isActive(this)};
g.h.ne=function(a){M5.dispatchEvent(new v5(M5,a))};
g.h.Bk=function(){return!(!g.Nd||g.Ec(10))};
g.h=N5.prototype;g.h.nu=function(){};
g.h.mu=function(){};
g.h.lu=function(){};
g.h.Lo=function(){};
g.h.fv=function(){return{}};
g.h.isActive=function(){return!0};g.A(O5,g.H);g.h=O5.prototype;g.h.GK=function(){this.Tc=Math.min(3E5,2*this.Tc);this.l();this.i&&this.start()};
g.h.start=function(){var a=this.Tc+15E3*Math.random();g.eo(this.g,a);this.i=(0,g.C)()+a};
g.h.stop=function(){this.g.stop();this.i=0};
g.h.isActive=function(){return this.g.isActive()};
g.h.reset=function(){this.g.stop();this.Tc=5E3};g.A(P5,N5);g.h=P5.prototype;g.h.subscribe=function(a,b,c){return this.l.subscribe(a,b,c)};
g.h.unsubscribe=function(a,b,c){return this.l.unsubscribe(a,b,c)};
g.h.zf=function(a){return this.l.Rg(a)};
g.h.N=function(a,b){return this.l.N.apply(this.l,arguments)};
g.h.dispose=function(){this.Za||(this.Za=!0,g.qf(this.l),Q5(this),g.qf(this.i),this.i=null)};
g.h.ea=function(){return this.Za};
g.h.connect=function(a,b,c){if(!this.g||2!=this.g.g){this.F="";this.i.stop();this.u=a||null;this.o=b||0;a=this.H+"/test";b=this.H+"/bind";var d=new s5(c?c.firstTestResults:null,c?c.secondTestResults:null,this.I),e=this.g;e&&(e.Sc=null);d.Sc=this;this.g=d;e?this.g.connect(a,b,this.A,e.l,e.Zh):c?this.g.connect(a,b,this.A,c.sessionId,c.arrayId):this.g.connect(a,b,this.A)}};
g.h.sendMessage=function(a,b){var c={_sc:a};b&&g.fc(c,b);this.i.isActive()||2==(this.g?this.g.g:0)?this.B.push(c):R5(this)&&D5(this.g,c)};
g.h.nu=function(){this.i.reset();this.u=null;this.o=0;if(this.B.length){var a=this.B;this.B=[];for(var b=0,c=a.length;b<c;++b)D5(this.g,a[b])}this.N("handlerOpened")};
g.h.lu=function(a){var b=2==a&&401==this.g.Ee;4==a||b||this.i.start();this.N("handlerError",a)};
g.h.Lo=function(a){if(!this.i.isActive())this.N("handlerClosed");else if(a)for(var b=0,c=a.length;b<c;++b){var d=a[b].map;d&&this.B.push(d)}};
g.h.fv=function(){var a={v:2};this.F&&(a.gsessionid=this.F);0!=this.o&&(a.ui=""+this.o);0!=this.D&&(a.ui=""+this.D);this.u&&g.fc(a,this.u);return a};
g.h.mu=function(a){"S"==a[0]?this.F=a[1]:"gracefulReconnect"==a[0]?(this.i.start(),z5(this.g)):this.N("handlerMessage",new Mpa(a[0],a[1]))};
g.h.tM=function(){this.i.isActive();var a=this.g,b=0;a.Sb&&b++;a.wd&&b++;0!=b||this.connect(this.u,this.o)};S5.prototype.o=function(a,b,c,d){b?a(d):a({text:c.responseText})};
S5.prototype.l=function(a,b){a(Error("Request error: "+b.status))};
S5.prototype.u=function(a){a(Error("request timed out"))};var Spa=(0,g.C)(),X5=null,a6=Array(50),$5=-1,b6=!1;g.A(c6,g.Q);c6.prototype.Ed=function(){return this.g};
c6.prototype.contains=function(a){return!!x4(this.g,a)};
c6.prototype.get=function(a){return a?y4(this.g,a):null};
c6.prototype.info=function(a){Z5(this.B,a)};g.A(e6,g.Q);var j8=[2E3,2E3,1E3,1E3,1E3,2E3,2E3,5E3,5E3,1E4];g.h=e6.prototype;g.h.start=function(){!this.g&&isNaN(this.za)&&this.LA()};
g.h.stop=function(){this.g&&(this.g.abort(),this.g=null);isNaN(this.za)||(g.Ip(this.za),this.za=NaN)};
g.h.T=function(){this.stop();e6.Ga.T.call(this)};
g.h.LA=function(){this.za=NaN;this.g=g.vq(T5(this.A,"/pairing/get_screen"),{method:"POST",qb:{pairing_code:this.u},timeout:5E3,onSuccess:(0,g.z)(this.vM,this),onError:(0,g.z)(this.uM,this),nd:(0,g.z)(this.wM,this)})};
g.h.vM=function(a,b){this.g=null;var c=b.screen||{};c.dialId=this.l;c.name=this.o;this.N("pairingComplete",new q4(c))};
g.h.uM=function(a){this.g=null;a.status&&404==a.status?this.i>=j8.length?this.N("pairingFailed",Error("DIAL polling timed out")):(a=j8[this.i],this.za=g.Gp((0,g.z)(this.LA,this),a),this.i++):this.N("pairingFailed",Error("Server error "+a.status))};
g.h.wM=function(){this.g=null;this.N("pairingFailed",Error("Server not responding"))};g.A(g6,c6);g.h=g6.prototype;g.h.start=function(){f6(this)&&this.N("screenChange");!g.$s("yt-remote-lounge-token-expiration")&&h6(this);g.Ip(this.i);this.i=g.Gp((0,g.z)(this.start,this),1E4)};
g.h.add=function(a,b){f6(this);d6(this,a);i6(this,!1);this.N("screenChange");b(a);a.token||h6(this)};
g.h.remove=function(a,b){var c=f6(this);Upa(this,a)&&(i6(this,!1),c=!0);b(a);c&&this.N("screenChange")};
g.h.Qn=function(a,b,c,d){var e=f6(this),f=this.get(a.id);f?(f.name!=b&&(f.name=b,i6(this,!1),e=!0),c(a)):d(Error("no such local screen."));e&&this.N("screenChange")};
g.h.T=function(){g.Ip(this.i);g6.Ga.T.call(this)};
g.h.WC=function(a){f6(this);var b=this.g.length;a=a&&a.screens||[];for(var c=0,d=a.length;c<d;++c){var e=a[c],f=this.get(e.screenId);f&&(f.token=e.loungeToken,--b)}i6(this,!b);b&&Z5(this.B,"Missed "+b+" lounge tokens.")};
g.h.VC=function(a){Z5(this.B,"Requesting lounge tokens failed: "+a)};g.A(k6,g.Q);g.h=k6.prototype;g.h.start=function(){var a=parseInt(g.$s("yt-remote-fast-check-period")||"0",10);(this.o=(0,g.C)()-144E5<a?0:a)?n6(this):(this.o=(0,g.C)()+3E5,g.Zs("yt-remote-fast-check-period",this.o),this.Kr())};
g.h.isEmpty=function(){return g.Yb(this.g)};
g.h.update=function(){j6("Updating availability on schedule.");var a=this.A(),b=g.Mb(this.g,function(c,d){return c&&!!y4(a,d)},this);
m6(this,b)};
g.h.T=function(){g.Ip(this.l);this.l=NaN;this.i&&(this.i.abort(),this.i=null);k6.Ga.T.call(this)};
g.h.Kr=function(){g.Ip(this.l);this.l=NaN;this.i&&this.i.abort();var a=o6(this);if(l4(a)){var b=T5(this.u,"/pairing/get_screen_availability");this.i=U5(this.u,b,{lounge_token:g.Sb(a).join(",")},(0,g.z)(this.kK,this,a),(0,g.z)(this.jK,this))}else m6(this,{}),n6(this)};
g.h.kK=function(a,b){this.i=null;var c=g.Sb(o6(this));if(g.sb(c,g.Sb(a))){c=b.screens||[];for(var d={},e=0,f=c.length;e<f;++e)d[a[c[e].loungeToken]]="online"==c[e].status;m6(this,d);n6(this)}else this.Lb("Changing Screen set during request."),this.Kr()};
g.h.jK=function(a){this.Lb("Screen availability failed: "+a);this.i=null;n6(this)};
g.h.Lb=function(a){Z5("OnlineScreenService",a)};g.A(p6,c6);g.h=p6.prototype;g.h.start=function(){this.l.start();this.i.start();this.g.length&&(this.N("screenChange"),this.i.isEmpty()||this.N("onlineScreenChange"))};
g.h.add=function(a,b,c){this.l.add(a,b,c)};
g.h.remove=function(a,b,c){this.l.remove(a,b,c);this.i.update()};
g.h.Qn=function(a,b,c,d){this.l.contains(a)?this.l.Qn(a,b,c,d):(a="Updating name of unknown screen: "+a.name,Z5(this.B,a),d(Error(a)))};
g.h.Ed=function(a){return a?this.g:g.gb(this.g,(0,g.Zd)(this.o,function(b){return!this.contains(b)},this))};
g.h.MA=function(){return(0,g.Zd)(this.Ed(!0),function(a){return!!this.i.g[a.id]},this)};
g.h.NA=function(a,b,c,d,e){this.info("getDialScreenByPairingCode "+a+" / "+b);var f=new e6(this.A,a,b,c);f.subscribe("pairingComplete",(0,g.z)(function(k){g.qf(f);d(q6(this,k))},this));
f.subscribe("pairingFailed",function(k){g.qf(f);e(k)});
f.start();return(0,g.z)(f.stop,f)};
g.h.yM=function(a,b,c,d){g.vq(T5(this.A,"/pairing/get_screen"),{method:"POST",qb:{pairing_code:a},timeout:5E3,onSuccess:(0,g.z)(function(e,f){var k=new q4(f.screen||{});if(!k.name||s6(this,k.name)){a:{var l=k.name;for(var m=2,n=b(l,m);s6(this,n);){m++;if(20<m)break a;n=b(l,m)}l=n}k.name=l}c(q6(this,k))},this),
onError:(0,g.z)(function(e){d(Error("pairing request failed: "+e.status))},this),
nd:(0,g.z)(function(){d(Error("pairing request timed out."))},this)})};
g.h.T=function(){g.qf(this.l);g.qf(this.i);p6.Ga.T.call(this)};
g.h.fD=function(){t6(this);this.N("screenChange");this.i.update()};
p6.prototype.dispose=p6.prototype.dispose;g.A(v6,g.Q);g.h=v6.prototype;g.h.Xm=function(a){this.l=a;this.N("sessionScreen",this.l)};
g.h.Id=function(a){this.ea()||(a&&w6(this,""+a),this.l=null,this.N("sessionScreen",null))};
g.h.info=function(a){Z5(this.P,a)};
g.h.PA=function(){return null};
g.h.Ur=function(a){var b=this.i;a?(b.displayStatus=new chrome.cast.ReceiverDisplayStatus(a,[]),b.displayStatus.showStop=!0):b.displayStatus=null;chrome.cast.setReceiverDisplayStatus(b,(0,g.z)(function(){this.info("Updated receiver status for "+b.friendlyName+": "+a)},this),(0,g.z)(function(){w6(this,"Failed to update receiver status for: "+b.friendlyName)},this))};
g.h.T=function(){this.Ur("");v6.Ga.T.call(this)};g.A(y6,v6);g.h=y6.prototype;g.h.Tr=function(a){if(this.g){if(this.g==a)return;w6(this,"Overriding cast sesison with new session object");this.g.removeUpdateListener(this.A);this.g.removeMessageListener("urn:x-cast:com.google.youtube.mdx",this.u)}this.g=a;this.g.addUpdateListener(this.A);this.g.addMessageListener("urn:x-cast:com.google.youtube.mdx",this.u);Ypa(this)};
g.h.bi=function(a){this.info("launchWithParams no-op for Cast: "+g.Hg(a))};
g.h.stop=function(){this.g?this.g.stop((0,g.z)(function(){this.Id()},this),(0,g.z)(function(){this.Id(Error("Failed to stop receiver app."))},this)):this.Id(Error("Stopping cast device witout session."))};
g.h.Ur=g.Ia;g.h.T=function(){this.info("disposeInternal");g.Ip(this.o);this.o=0;this.g&&(this.g.removeUpdateListener(this.A),this.g.removeMessageListener("urn:x-cast:com.google.youtube.mdx",this.u));this.g=null;y6.Ga.T.call(this)};
g.h.jL=function(a,b){if(!this.ea())if(b){var c=m4(b);if(g.Pa(c)){var d=""+c.type;c=c.data||{};this.info("onYoutubeMessage_: "+d+" "+g.Hg(c));switch(d){case "mdxSessionStatus":x6(this,c.screenId);break;default:w6(this,"Unknown youtube message: "+d)}}else w6(this,"Unable to parse message.")}else w6(this,"No data in message.")};
g.h.yv=function(a,b,c,d){r6(this.F,this.i.label,a,this.i.friendlyName,(0,g.z)(function(e){e?b(e):0<=d?(w6(this,"Screen "+a+" appears to be offline. "+d+" retries left."),g.Gp((0,g.z)(this.yv,this,a,b,c,d-1),300)):c(Error("Unable to fetch screen."))},this),c)};
g.h.PA=function(){return this.g};
g.h.zM=function(a){this.ea()||a||(w6(this,"Cast session died."),this.Id())};g.A(z6,v6);g.h=z6.prototype;g.h.Tr=function(a){this.o=a;this.o.addUpdateListener(this.I)};
g.h.bi=function(a){this.u=a;this.B()};
g.h.stop=function(){this.g();this.g=g.Ia;g.Ip(this.A);this.o?this.o.stop((0,g.z)(this.Id,this,null),(0,g.z)(this.Id,this,"Failed to stop DIAL device.")):this.Id()};
g.h.T=function(){this.g();this.g=g.Ia;g.Ip(this.A);this.o&&this.o.removeUpdateListener(this.I);this.o=null;z6.Ga.T.call(this)};
g.h.CM=function(a){this.ea()||a||(w6(this,"DIAL session died."),this.g(),this.g=g.Ia,this.Id())};
g.h.Pp=function(a){this.H=w4();if(this.u){var b=new chrome.cast.DialLaunchResponse(!0,B6(this));a(b);A6(this)}else this.B=(0,g.z)(function(){g.Ip(this.A);this.B=g.Ia;this.A=NaN;var c=new chrome.cast.DialLaunchResponse(!0,B6(this));a(c);A6(this)},this),this.A=g.Gp((0,g.z)(function(){this.B()},this),100)};
g.h.CD=function(a,b,c){r6(this.F,this.D.receiver.label,a,this.i.friendlyName,(0,g.z)(function(d){d&&d.token?(this.Xm(d),b(new chrome.cast.DialLaunchResponse(!1))):this.Pp(b,c)},this),(0,g.z)(function(d){w6(this,"Failed to get DIAL screen: "+d);
this.Pp(b,c)},this))};g.A(C6,v6);C6.prototype.stop=function(){this.Id()};
C6.prototype.Tr=g.Ia;C6.prototype.bi=function(){g.Ip(this.g);this.g=NaN;var a=y4(this.F.Ed(),this.i.label);a?this.Xm(a):this.Id(Error("No such screen"))};
C6.prototype.T=function(){g.Ip(this.g);this.g=NaN;C6.Ga.T.call(this)};g.A(D6,g.Q);g.h=D6.prototype;
g.h.init=function(a,b){chrome.cast.timeout.requestSession=3E4;var c=new chrome.cast.SessionRequest(this.B);this.D||(c.dialRequest=new chrome.cast.DialRequest("YouTube"));var d=chrome.cast.AutoJoinPolicy.TAB_AND_ORIGIN_SCOPED,e=a?chrome.cast.DefaultActionPolicy.CAST_THIS_TAB:chrome.cast.DefaultActionPolicy.CREATE_SESSION;c=new chrome.cast.ApiConfig(c,(0,g.z)(this.Dy,this),(0,g.z)(this.TJ,this),d,e);c.customDialLaunchCallback=(0,g.z)(this.dI,this);chrome.cast.initialize(c,(0,g.z)(function(){this.ea()||
(chrome.cast.addReceiverActionListener(this.o),Ppa(),this.i.subscribe("onlineScreenChange",(0,g.z)(this.OA,this)),this.l=I6(this),chrome.cast.setCustomReceivers(this.l,g.Ia,(0,g.z)(function(f){this.Lb("Failed to set initial custom receivers: "+g.Hg(f))},this)),this.N("yt-remote-cast2-availability-change",G6(this)),b(!0))},this),(0,g.z)(function(f){this.Lb("Failed to initialize API: "+g.Hg(f));
b(!1)},this))};
g.h.LL=function(a,b){F6("Setting connected screen ID: "+a+" -> "+b);if(this.g){var c=this.g.l;if(!a||c&&c.id!=a)F6("Unsetting old screen status: "+this.g.i.friendlyName),H6(this,null)}if(a&&b){if(!this.g){c=y4(this.i.Ed(),a);if(!c){F6("setConnectedScreenStatus: Unknown screen.");return}var d=E6(this,c);d||(F6("setConnectedScreenStatus: Connected receiver not custom..."),d=new chrome.cast.Receiver(c.uuid?c.uuid:c.id,c.name),d.receiverType=chrome.cast.ReceiverType.CUSTOM,this.l.push(d),chrome.cast.setCustomReceivers(this.l,
g.Ia,(0,g.z)(function(e){this.Lb("Failed to set initial custom receivers: "+g.Hg(e))},this)));
F6("setConnectedScreenStatus: new active receiver: "+d.friendlyName);H6(this,new C6(this.i,d),!0)}this.g.Ur(b)}else F6("setConnectedScreenStatus: no screen.")};
g.h.ML=function(a){this.ea()?this.Lb("Setting connection data on disposed cast v2"):this.g?this.g.bi(a):this.Lb("Setting connection data without a session")};
g.h.BM=function(){this.ea()?this.Lb("Stopping session on disposed cast v2"):this.g?(this.g.stop(),H6(this,null)):F6("Stopping non-existing session")};
g.h.requestSession=function(){chrome.cast.requestSession((0,g.z)(this.Dy,this),(0,g.z)(this.pK,this))};
g.h.T=function(){this.i.unsubscribe("onlineScreenChange",(0,g.z)(this.OA,this));window.chrome&&chrome.cast&&chrome.cast.removeReceiverActionListener(this.o);g.db(g.x("yt.mdx.remote.debug.handlers_")||[],V5);g.qf(this.g);D6.Ga.T.call(this)};
g.h.Lb=function(a){Z5("Controller",a)};
g.h.Ey=function(a,b){this.g==a&&(b||H6(this,null),this.N("yt-remote-cast2-session-change",b))};
g.h.PJ=function(a,b){if(!this.ea())if(a)switch(a.friendlyName=chrome.cast.unescape(a.friendlyName),F6("onReceiverAction_ "+a.label+" / "+a.friendlyName+"-- "+b),b){case chrome.cast.ReceiverAction.CAST:if(this.g)if(this.g.i.label!=a.label)F6("onReceiverAction_: Stopping active receiver: "+this.g.i.friendlyName),this.g.stop();else{F6("onReceiverAction_: Casting to active receiver.");this.g.l&&this.N("yt-remote-cast2-session-change",this.g.l);break}switch(a.receiverType){case chrome.cast.ReceiverType.CUSTOM:H6(this,
new C6(this.i,a));break;case chrome.cast.ReceiverType.DIAL:H6(this,new z6(this.i,a,this.A));break;case chrome.cast.ReceiverType.CAST:H6(this,new y6(this.i,a));break;default:this.Lb("Unknown receiver type: "+a.receiverType)}break;case chrome.cast.ReceiverAction.STOP:this.g&&this.g.i.label==a.label?this.g.stop():this.Lb("Stopping receiver w/o session: "+a.friendlyName)}else this.Lb("onReceiverAction_ called without receiver.")};
g.h.dI=function(a){if(this.ea())return Promise.reject(Error("disposed"));var b=a.receiver;b.receiverType!=chrome.cast.ReceiverType.DIAL&&(this.Lb("Not DIAL receiver: "+b.friendlyName),b.receiverType=chrome.cast.ReceiverType.DIAL);var c=this.g?this.g.i:null;if(!c||c.label!=b.label)return this.Lb("Receiving DIAL launch request for non-clicked DIAL receiver: "+b.friendlyName),Promise.reject(Error("illegal DIAL launch"));if(c&&c.label==b.label&&c.receiverType!=chrome.cast.ReceiverType.DIAL){if(this.g.l)return F6("Reselecting dial screen."),
this.N("yt-remote-cast2-session-change",this.g.l),Promise.resolve(new chrome.cast.DialLaunchResponse(!1));this.Lb('Changing CAST intent from "'+c.receiverType+'" to "dial" for '+b.friendlyName);H6(this,new z6(this.i,b,this.A))}b=this.g;b.D=a;return b.D.appState==chrome.cast.DialAppState.RUNNING?new Promise((0,g.z)(b.CD,b,(b.D.extraData||{}).screenId||null)):new Promise((0,g.z)(b.Pp,b))};
g.h.Dy=function(a){if(!this.ea()){F6("New cast session ID: "+a.sessionId);var b=a.receiver;if(b.receiverType!=chrome.cast.ReceiverType.CUSTOM){if(!this.g)if(b.receiverType==chrome.cast.ReceiverType.CAST)F6("Got resumed cast session before resumed mdx connection."),b.friendlyName=chrome.cast.unescape(b.friendlyName),H6(this,new y6(this.i,b),!0);else{this.Lb("Got non-cast session without previous mdx receiver event, or mdx resume.");return}var c=this.g.i,d=y4(this.i.Ed(),c.label);d&&r4(d,b.label)&&
c.receiverType!=chrome.cast.ReceiverType.CAST&&b.receiverType==chrome.cast.ReceiverType.CAST&&(F6("onSessionEstablished_: manual to cast session change "+b.friendlyName),g.qf(this.g),this.g=new y6(this.i,b),this.g.subscribe("sessionScreen",(0,g.z)(this.Ey,this,this.g)),this.g.bi(null));this.g.Tr(a)}}};
g.h.AM=function(){return this.g?this.g.PA():null};
g.h.pK=function(a){this.ea()||(this.Lb("Failed to estabilish a session: "+g.Hg(a)),a.code!=chrome.cast.ErrorCode.CANCEL&&H6(this,null))};
g.h.TJ=function(a){F6("Receiver availability updated: "+a);if(!this.ea()){var b=G6(this);this.u=a==chrome.cast.ReceiverAvailability.AVAILABLE;G6(this)!=b&&this.N("yt-remote-cast2-availability-change",G6(this))}};
g.h.OA=function(){this.ea()||(this.l=I6(this),F6("Updating custom receivers: "+g.Hg(this.l)),chrome.cast.setCustomReceivers(this.l,g.Ia,(0,g.z)(function(){this.Lb("Failed to set custom receivers.")},this)),this.N("yt-remote-cast2-availability-change",G6(this)))};
D6.prototype.setLaunchParams=D6.prototype.ML;D6.prototype.setConnectedScreenStatus=D6.prototype.LL;D6.prototype.stopSession=D6.prototype.BM;D6.prototype.getCastSession=D6.prototype.AM;D6.prototype.requestSession=D6.prototype.requestSession;D6.prototype.init=D6.prototype.init;D6.prototype.dispose=D6.prototype.dispose;var R6=[];Z6.prototype.reset=function(a){this.listId="";this.index=-1;this.videoId="";$6(this);this.volume=-1;this.muted=!1;a&&(this.index=a.index,this.listId=a.listId,this.videoId=a.videoId,this.playerState=a.playerState,this.volume=a.volume,this.muted=a.muted,this.audioTrackId=a.audioTrackId,this.g=a.trackData,this.Ge=a.hasPrevious,this.hasNext=a.hasNext,this.B=a.playerTime,this.A=a.playerTimeAt,this.o=a.seekableStart,this.i=a.seekableEnd,this.D=a.duration,this.F=a.loadedTime,this.l=a.liveIngestionTime,this.u=
!isNaN(this.l))};
Z6.prototype.isAdPlaying=function(){return 1081==this.playerState};
Z6.prototype.getDuration=function(){return this.u?this.D+a7(this):this.D};
Z6.prototype.clone=function(){return new Z6(e7(this))};g.A(h7,g.Q);g.h=h7.prototype;g.h.play=function(){1==this.g?(this.i?this.i.play(null,g.Ia,p7(this,"play")):n7(this,"play"),m7(this,1,c7(i7(this))),this.N("remotePlayerChange")):k7(this,this.play)};
g.h.pause=function(){1==this.g?(this.i?this.i.pause(null,g.Ia,p7(this,"pause")):n7(this,"pause"),m7(this,2,c7(i7(this))),this.N("remotePlayerChange")):k7(this,this.pause)};
g.h.seekTo=function(a){if(1==this.g){if(this.i){var b=i7(this),c=new chrome.cast.media.SeekRequest;c.currentTime=a;c.resumeState=1==b.playerState||3==b.playerState?chrome.cast.media.ResumeState.PLAYBACK_START:chrome.cast.media.ResumeState.PLAYBACK_PAUSE;this.i.seek(c,g.Ia,p7(this,"seekTo",{newTime:a}))}else n7(this,"seekTo",{newTime:a});m7(this,3,a);this.N("remotePlayerChange")}else k7(this,g.Sa(this.seekTo,a))};
g.h.stop=function(){if(1==this.g){this.i?this.i.stop(null,g.Ia,p7(this,"stopVideo")):n7(this,"stopVideo");var a=i7(this);a.index=-1;a.videoId="";$6(a);l7(this,a);this.N("remotePlayerChange")}else k7(this,this.stop)};
g.h.setVolume=function(a,b){if(1==this.g){var c=i7(this);if(this.l){if(c.volume!=a){var d=Math.round(a)/100;this.l.setReceiverVolumeLevel(d,(0,g.z)(function(){Z5("CP","set receiver volume: "+d)},this),(0,g.z)(function(){this.Lb("failed to set receiver volume.")},this))}c.muted!=b&&this.l.setReceiverMuted(b,(0,g.z)(function(){Z5("CP","set receiver muted: "+b)},this),(0,g.z)(function(){this.Lb("failed to set receiver muted.")},this))}else{var e={volume:a,
muted:b};-1!=c.volume&&(e.delta=a-c.volume);n7(this,"setVolume",e)}c.muted=b;c.volume=a;l7(this,c)}else k7(this,g.Sa(this.setVolume,a,b))};
g.h.Nz=function(a,b){if(1==this.g){var c=i7(this),d={videoId:a};b&&(c.g={trackName:b.name,languageCode:b.languageCode,sourceLanguageCode:b.translationLanguage?b.translationLanguage.languageCode:"",languageName:b.languageName,kind:b.kind},d.style=g.Hg(b.style),g.fc(d,c.g));n7(this,"setSubtitlesTrack",d);l7(this,c)}else k7(this,g.Sa(this.Nz,a,b))};
g.h.setAudioTrack=function(a,b){if(1==this.g){var c=b.getLanguageInfo().getId();n7(this,"setAudioTrack",{videoId:a,audioTrackId:c});var d=i7(this);d.audioTrackId=c;l7(this,d)}else k7(this,g.Sa(this.setAudioTrack,a,b))};
g.h.playVideo=function(a,b,c,d,e,f,k){var l=i7(this);c=c||0;var m={videoId:a,currentIndex:c};d7(l,a,c);g.Ea(b)&&(b7(l,b),m.currentTime=b);g.Ea(d)&&(m.listId=d);null!=e&&(m.playerParams=e);null!=f&&(m.clickTrackingParams=f);null!=k&&(m.locationInfo=g.Hg(k));n7(this,"setPlaylist",m);d||l7(this,l)};
g.h.fn=function(a,b){if(1==this.g){if(a&&b){var c=i7(this);d7(c,a,b);l7(this,c)}n7(this,"previous")}else k7(this,g.Sa(this.fn,a,b))};
g.h.nextVideo=function(a,b){if(1==this.g){if(a&&b){var c=i7(this);d7(c,a,b);l7(this,c)}n7(this,"next")}else k7(this,g.Sa(this.nextVideo,a,b))};
g.h.Lu=function(){1==this.g?n7(this,"dismissAutoplay"):k7(this,this.Lu)};
g.h.dispose=function(){if(3!=this.g){var a=this.g;this.g=3;this.N("proxyStateChange",a,this.g)}h7.Ga.dispose.call(this)};
g.h.T=function(){j7(this);this.o=null;this.u.clear();g7(this,null);h7.Ga.T.call(this)};
g.h.Os=function(a){if((a!=this.g||2==a)&&3!=this.g&&0!=a){var b=this.g;this.g=a;this.N("proxyStateChange",b,a);if(1==a)for(;!this.u.isEmpty();)b=a=this.u,0==b.g.length&&(b.g=b.i,b.g.reverse(),b.i=[]),a.g.pop().apply(this);else 3==a&&this.dispose()}};
g.h.MJ=function(a,b){this.N(a,b)};
g.h.JH=function(a){if(!a)this.ik(null),g7(this,null);else if(this.l.receiver.volume){a=this.l.receiver.volume;var b=i7(this),c=Math.round(100*a.level||0);if(b.volume!=c||b.muted!=a.muted)Z5("CP","Cast volume update: "+a.level+(a.muted?" muted":"")),b.volume=c,b.muted=!!a.muted,l7(this,b)}};
g.h.ik=function(a){Z5("CP","Cast media: "+!!a);this.i&&this.i.removeUpdateListener(this.D);if(this.i=a)this.i.addUpdateListener(this.D),o7(this),this.N("remotePlayerChange")};
g.h.IH=function(a){a?(o7(this),this.N("remotePlayerChange")):this.ik(null)};
g.h.xs=function(){n7(this,"sendDebugCommand",{debugCommand:"stats4nerds "})};
g.h.VH=function(){var a=V6();a&&g7(this,a)};
g.h.Lb=function(a){Z5("CP",a)};g.A(q7,g.Q);g.h=q7.prototype;
g.h.connect=function(a,b){if(b){var c=b.listId,d=b.videoId,e=b.playerParams,f=b.clickTrackingParams,k=b.index,l={videoId:d},m=b.currentTime,n=b.locationInfo;g.Ea(m)&&(l.currentTime=5>=m?0:m);e&&(l.playerParams=e);n&&(l.locationInfo=n);f&&(l.clickTrackingParams=f);c&&(l.listId=c);g.Ea(k)&&(l.currentIndex=k);c&&(this.Qa.listId=c);this.Qa.videoId=d;this.Qa.index=k||0;this.Qa.state=3;b7(this.Qa,m);this.o="UNSUPPORTED";r7("Connecting with setPlaylist and params: "+g.Hg(l));this.g.connect({method:"setPlaylist",
params:g.Hg(l)},a,E4())}else r7("Connecting without params"),this.g.connect({},a,E4());eqa(this)};
g.h.dispose=function(){this.ea()||(this.N("beforeDispose"),s7(this,3));q7.Ga.dispose.call(this)};
g.h.T=function(){t7(this);v7(this);u7(this);g.Ip(this.F);this.F=NaN;g.Ip(this.H);this.H=NaN;this.l=null;g.wr(this.O);this.O.length=0;this.g.dispose();q7.Ga.T.call(this);this.o=this.B=this.i=this.Qa=this.g=null};
g.h.PC=function(){this.A(2)};
g.h.NH=function(){r7("Channel opened");this.M&&(this.M=!1,u7(this),this.P=g.Gp((0,g.z)(function(){r7("Timing out waiting for a screen.");this.A(1)},this),15E3));
Gpa(Npa(this.g),this.V)};
g.h.KH=function(){r7("Channel closed");isNaN(this.u)?H4(!0):H4();this.dispose()};
g.h.LH=function(a){H4();isNaN(this.D())?(r7("Channel error: "+a+" without reconnection"),this.dispose()):(this.M=!0,r7("Channel error: "+a+" with reconnection in "+this.D()+" ms"),s7(this,2))};
g.h.MH=function(a){a.params?r7("Received: action="+a.action+", params="+g.Hg(a.params)):r7("Received: action="+a.action+" {}");switch(a.action){case "loungeStatus":a=m4(a.params.devices);this.i=(0,g.G)(a,function(c){return new p4(c)});
a=!!g.Ya(this.i,function(c){return"LOUNGE_SCREEN"==c.type});
y7(this,a);break;case "loungeScreenDisconnected":g.eb(this.i,function(c){return"LOUNGE_SCREEN"==c.type});
y7(this,!1);break;case "remoteConnected":var b=new p4(m4(a.params.device));g.Ya(this.i,function(c){return b?c.id==b.id:!1})||upa(this.i,b);
break;case "remoteDisconnected":b=new p4(m4(a.params.device));g.eb(this.i,function(c){return b?c.id==b.id:!1});
break;case "gracefulDisconnect":break;case "playlistModified":z7(this,a);break;case "nowPlaying":hqa(this,a);break;case "onStateChange":A7(this,a);break;case "onAdStateChange":iqa(this,a);break;case "onVolumeChanged":jqa(this,a);break;case "onSubtitlesTrackChanged":gqa(this,a);break;case "nowAutoplaying":kqa(this,a);break;case "autoplayDismissed":this.N("autoplayDismissed");break;case "autoplayUpNext":this.B=a.params.videoId||null;this.N("autoplayUpNext",this.B);break;case "onAutoplayModeChanged":this.o=
a.params.autoplayMode;this.N("autoplayModeChange",this.o);"DISABLED"==this.o&&this.N("autoplayDismissed");break;case "onHasPreviousNextChanged":lqa(this,a);break;case "requestAssistedSignIn":this.N("assistedSignInRequested",a.params.authCode);break;default:r7("Unrecognized action: "+a.action)}};
g.h.AL=function(){if(this.l){var a=this.l;this.l=null;this.Qa.videoId!=a&&w7(this,"getNowPlaying")}};
q7.prototype.subscribe=q7.prototype.subscribe;q7.prototype.unsubscribeByKey=q7.prototype.zf;q7.prototype.ca=function(){var a=3;this.ea()||(a=0,isNaN(this.D())?R5(this.g)&&isNaN(this.u)&&(a=1):a=2);return a};
q7.prototype.getProxyState=q7.prototype.ca;q7.prototype.A=function(a){r7("Disconnecting with "+a);t7(this);this.N("beforeDisconnect",a);1==a&&H4();Q5(this.g,a);this.dispose()};
q7.prototype.disconnect=q7.prototype.A;q7.prototype.X=function(){var a=this.Qa;this.l&&(a=this.Qa.clone(),d7(a,this.l,a.index));return e7(a)};
q7.prototype.getPlayerContextData=q7.prototype.X;
q7.prototype.la=function(a){var b=new Z6(a);b.videoId&&b.videoId!=this.Qa.videoId&&(this.l=b.videoId,g.Ip(this.F),this.F=g.Gp((0,g.z)(this.AL,this),5E3));var c=[];this.Qa.listId==b.listId&&this.Qa.videoId==b.videoId&&this.Qa.index==b.index||c.push("remoteQueueChange");this.Qa.playerState==b.playerState&&this.Qa.volume==b.volume&&this.Qa.muted==b.muted&&c7(this.Qa)==c7(b)&&g.Hg(this.Qa.g)==g.Hg(b.g)||c.push("remotePlayerChange");this.Qa.reset(a);(0,g.B)(c,function(d){this.N(d)},this)};
q7.prototype.setPlayerContextData=q7.prototype.la;q7.prototype.R=function(){var a=this.g.A.id,b=g.Ya(this.i,function(c){return"REMOTE_CONTROL"==c.type&&c.id!=a});
return b?b.id:""};
q7.prototype.getOtherConnectedRemoteId=q7.prototype.R;q7.prototype.D=function(){var a=this.g;return a.i.isActive()?a.i.i-(0,g.C)():NaN};
q7.prototype.getReconnectTimeout=q7.prototype.D;q7.prototype.aa=function(){return this.o||"UNSUPPORTED"};
q7.prototype.getAutoplayMode=q7.prototype.aa;q7.prototype.Y=function(){return this.B||""};
q7.prototype.getAutoplayVideoId=q7.prototype.Y;q7.prototype.ua=function(){if(!isNaN(this.D())){var a=this.g.i;g.fo(a.g);a.start()}};
q7.prototype.reconnect=q7.prototype.ua;q7.prototype.ka=function(a,b){w7(this,a,b);x7(this)};
q7.prototype.sendMessage=q7.prototype.ka;g.A(B7,c6);g.h=B7.prototype;g.h.Ed=function(a){return this.Ic.$_gs(a)};
g.h.contains=function(a){return!!this.Ic.$_c(a)};
g.h.get=function(a){return this.Ic.$_g(a)};
g.h.start=function(){this.Ic.$_st()};
g.h.add=function(a,b,c){this.Ic.$_a(a,b,c)};
g.h.remove=function(a,b,c){this.Ic.$_r(a,b,c)};
g.h.Qn=function(a,b,c,d){this.Ic.$_un(a,b,c,d)};
g.h.T=function(){for(var a=0,b=this.i.length;a<b;++a)this.Ic.$_ubk(this.i[a]);this.i.length=0;this.Ic=null;B7.Ga.T.call(this)};
g.h.xM=function(){this.N("screenChange")};
g.h.qJ=function(){this.N("onlineScreenChange")};
p6.prototype.$_st=p6.prototype.start;p6.prototype.$_gspc=p6.prototype.yM;p6.prototype.$_gsppc=p6.prototype.NA;p6.prototype.$_c=p6.prototype.contains;p6.prototype.$_g=p6.prototype.get;p6.prototype.$_a=p6.prototype.add;p6.prototype.$_un=p6.prototype.Qn;p6.prototype.$_r=p6.prototype.remove;p6.prototype.$_gs=p6.prototype.Ed;p6.prototype.$_gos=p6.prototype.MA;p6.prototype.$_s=p6.prototype.subscribe;p6.prototype.$_ubk=p6.prototype.zf;var C7=null,D7=null,T7=null,H7=[];g.t(W7,g.H);g.h=W7.prototype;
g.h.T=function(){g.H.prototype.T.call(this);this.o.stop();this.A.stop();this.I.stop();this.M();this.g.unsubscribe("proxyStateChange",this.Ay,this);this.g.unsubscribe("remotePlayerChange",this.kk,this);this.g.unsubscribe("remoteQueueChange",this.Ym,this);this.g.unsubscribe("autoplayUpNext",this.Zx,this);this.g.unsubscribe("previousNextChange",this.wy,this);this.g.unsubscribe("nowAutoplaying",this.ry,this);this.g.unsubscribe("autoplayDismissed",this.Yx,this);this.g=this.u=null};
g.h.Xw=function(a,b){for(var c=[],d=1;d<arguments.length;++d)c[d-1]=arguments[d];if(2!=this.g.g)if($7(this)){if(!i7(this.g).isAdPlaying()||"control_seek"!=a)switch(a){case "control_toggle_play_pause":1==i7(this.g).playerState?this.g.pause():this.g.play();break;case "control_play":this.g.play();break;case "control_pause":this.g.pause();break;case "control_seek":this.H.wj(c[0],c[1]);break;case "control_subtitles_set_track":a8(this,c[0]);break;case "control_set_audio_track":c=c[0],$7(this)&&this.g.setAudioTrack(this.i.getVideoData(1).videoId,
c)}}else switch(a){case "control_toggle_play_pause":case "control_play":case "control_pause":c=this.i.getCurrentTime();b8(this,0==c?void 0:c);break;case "control_seek":b8(this,c[0]);break;case "control_subtitles_set_track":a8(this,c[0]);break;case "control_set_audio_track":c=c[0],$7(this)&&this.g.setAudioTrack(this.i.getVideoData(1).videoId,c)}};
g.h.HH=function(a){this.I.LC(a)};
g.h.gM=function(a){this.Xw("control_subtitles_set_track",g.Yb(a)?null:a)};
g.h.Zz=function(){var a=this.i.getOption("captions","track");g.Yb(a)||a8(this,a)};
g.h.my=function(a){if($7(this)){this.g.unsubscribe("remotePlayerChange",this.kk,this);var b=Math.round(a.volume);a=!!a.muted;var c=i7(this.g);if(b!=c.volume||a!=c.muted)this.g.setVolume(b,a),this.P.start();this.g.subscribe("remotePlayerChange",this.kk,this)}};
g.h.HI=function(){g.Yb(this.B)||c8(this,this.B);this.D=!1};
g.h.Ay=function(a,b){this.A.stop();2==b&&this.Yz()};
g.h.kk=function(){if($7(this)){this.o.stop();var a=i7(this.g);switch(a.playerState){case 1080:case 1081:case 1084:case 1085:this.u.nm=1;break;case 1082:case 1083:this.u.nm=0;break;default:this.u.nm=-1}switch(a.playerState){case 1081:case 1:Y7(this,new g.BC(8));this.Xz();break;case 1085:case 3:Y7(this,new g.BC(9));break;case 1083:case 0:Y7(this,new g.BC(2));this.H.stop();X7(this,this.i.getVideoData().lengthSeconds);break;case 1084:Y7(this,new g.BC(4));break;case 2:Y7(this,new g.BC(4));X7(this,c7(a));
break;case -1:Y7(this,new g.BC(64));break;case -1E3:Y7(this,new g.BC(128,{errorCode:"mdx.remoteerror",message:"This video is not available for remote playback."}))}a=i7(this.g).g;var b=this.B;(a||b?a&&b&&a.trackName==b.trackName&&a.languageCode==b.languageCode&&a.languageName==b.languageName&&a.kind==b.kind:1)||(this.B=a,c8(this,a));a=i7(this.g);-1==a.volume||Math.round(this.i.getVolume())==a.volume&&this.i.isMuted()==a.muted||this.P.isActive()||this.yA()}else Z7(this)};
g.h.wy=function(){this.i.N("mdxpreviousnextchange")};
g.h.Ym=function(){$7(this)||Z7(this)};
g.h.XB=function(){this.g.Lu()};
g.h.Zx=function(a){a&&(a=g.vq("/watch_queue_ajax",{method:"GET",Ec:{action_get_watch_queue_item:1,video_id:a},onSuccess:(0,g.z)(this.RK,this)}))&&(this.M=(0,g.z)(a.abort,a))};
g.h.RK=function(a,b){var c=new g.FA(g.W(this.i),{videoId:b.videoId,title:b.title,author:b.author,murlmq_webp:b.url});this.suggestion=c;this.i.N("mdxautoplayupnext",c)};
g.h.ry=function(a){isNaN(a)||this.i.N("mdxnowautoplaying",a)};
g.h.Yx=function(){this.i.N("mdxautoplaycanceled")};
g.h.nF=function(a,b){-1==i7(this.g).playerState?b8(this,a):b&&this.g.seekTo(a)};
g.h.yA=function(){if($7(this)){var a=i7(this.g);this.l.Na(this.O);a.muted?this.i.mute():this.i.unMute();this.i.setVolume(a.volume);this.O=this.l.K(this.i,"onVolumeChange",this.my)}};
g.h.Xz=function(){this.o.stop();if(!this.g.ea()){var a=i7(this.g);1==a.playerState&&Y7(this,new g.BC(8));X7(this,c7(a));this.o.start()}};
g.h.Yz=function(){this.A.stop();this.o.stop();var a=this.g.o.getReconnectTimeout();2==this.g.g&&!isNaN(a)&&this.A.start()};g.t(f8,g.U);f8.prototype.u=function(a){e8(this,a.state)};g.t(g8,g.XS);g8.prototype.I=function(){var a=this.l.getOption("remote","receivers");a&&1<a.length&&!this.l.getOption("remote","quickCast")?(this.F=g.ub(a,this.A,this),g.YS(this,(0,g.G)(a,this.A)),a=this.l.getOption("remote","currentReceiver"),this.me(this.A(a)),this.enable(!0)):this.enable(!1)};
g8.prototype.A=function(a){return a.key};
g8.prototype.le=function(a){return"cast-selector-receiver"==a?"Cast...":this.F[a].name};
g8.prototype.Kc=function(a){g.XS.prototype.Kc.call(this,a);this.l.setOption("remote","currentReceiver",this.F[a]);this.o.gb()};g.t(h8,g.QJ);g.h=h8.prototype;g.h.create=function(){qqa(g.zy(g.W(this.player)));this.u.push(g.Np("yt-remote-before-disconnect",this.EH,this));this.u.push(g.Np("yt-remote-connection-change",this.UJ,this));this.u.push(g.Np("yt-remote-receiver-availability-change",this.yy,this));this.u.push(g.Np("yt-remote-auto-connect",this.SJ,this));this.u.push(g.Np("yt-remote-receiver-resumed",this.RJ,this));this.yy()};
g.h.load=function(){this.player.cancelPlayback();g.QJ.prototype.load.call(this);this.o=new W7(this,this.player,this.g);var a=(a=V7())?a.currentTime:0;var b=S7()?new h7(N7(),void 0):null;0==a&&b&&(a=c7(i7(b)));0!=a&&this.pd(a);d8(this,this.Vj,this.Vj);g.aX(this.player.app,6)};
g.h.unload=function(){this.player.N("mdxautoplaycanceled");this.l=this.i;g.rf(this.o,this.g);this.g=this.o=null;g.QJ.prototype.unload.call(this);g.aX(this.player.app,5)};
g.h.T=function(){g.Op(this.u);g.QJ.prototype.T.call(this)};
g.h.Re=function(a,b){for(var c=[],d=1;d<arguments.length;++d)c[d-1]=arguments[d];this.loaded&&this.o.Xw.apply(this.o,[a].concat(g.ea(c)))};
g.h.getAdState=function(){return this.nm};
g.h.HC=function(){return this.loaded?this.o.suggestion:null};
g.h.Ge=function(){return this.g?i7(this.g).Ge:!1};
g.h.hasNext=function(){return this.g?i7(this.g).hasNext:!1};
g.h.pd=function(a,b){this.D=a||0;this.player.N("progresssync",a,b)};
g.h.getCurrentTime=function(){return this.D};
g.h.getProgressState=function(){var a=i7(this.g),b=this.player.getVideoData();return{allowSeeking:g.R(g.W(this.player).experiments,"web_player_mdx_allow_seeking_change_killswitch")?this.player.ec():!a.isAdPlaying()&&this.player.ec(),clipEnd:b.clipEnd,clipStart:b.clipStart,current:this.getCurrentTime(),displayedStart:-1,duration:a.getDuration(),ingestionTime:a.u?a.l+a7(a):a.l,isAtLiveHead:1>=(a.u?a.i+a7(a):a.i)-this.getCurrentTime(),loaded:a.F,seekableEnd:a.u?a.i+a7(a):a.i,seekableStart:0<a.o?a.o+
a7(a):a.o}};
g.h.nextVideo=function(){this.g&&this.g.nextVideo()};
g.h.fn=function(){this.g&&this.g.fn()};
g.h.EH=function(a){1==a&&(this.B=this.g?i7(this.g):null)};
g.h.UJ=function(){var a=S7()?new h7(N7(),void 0):null;if(a){var b=this.l;this.loaded&&this.unload();this.g=a;this.B=null;b.key!=this.i.key&&(this.l=b,this.load())}else g.qf(this.g),this.g=null,this.loaded&&(this.unload(),(a=this.B)&&a.videoId==this.player.getVideoData().videoId&&this.player.cueVideoById(a.videoId,c7(a)));this.player.N("videodatachange","newdata",this.player.getVideoData(),3)};
g.h.yy=function(){this.A=[this.i].concat(rqa());var a=O7()||this.i;i8(this,a);this.player.ma("onMdxReceiversChange")};
g.h.SJ=function(){var a=O7();i8(this,a)};
g.h.RJ=function(){this.l=O7()};
g.h.ac=function(a,b){switch(a){case "casting":return this.loaded;case "receivers":return this.A;case "currentReceiver":return b&&("cast-selector-receiver"==b.key?X6():i8(this,b)),this.loaded?this.l:this.i;case "quickCast":return 2==this.A.length&&"cast-selector-receiver"==this.A[1].key?(b&&X6(),!0):!1}};
g.h.xs=function(){this.g.xs()};
g.h.Ob=function(){return!1};
g.h.getOptions=function(){return["casting","receivers","currentReceiver","quickCast"]};g.nU.remote=h8;})(_yt_player);
